ExtremeFLOW/neko

- .github/workflows/develop.yml
- src/math/bcknd/device/device_math.F90
- Work on CUDA CI
- Fixes
- More fixes
- Don't use ifort flags with gcc...
- Standard fixes
- Add dist target for cuda CI
> Add CUDA CI

- doc/Doxyfile.in
- doc/Makefile.am
- Project description
- Remove nonexistent input directories
- Add make dependency on input files, so edit -> remake cycle works
> Improve Doxygen build

- src/math/bcknd/device/cuda/ax_helm.cu
- src/math/bcknd/device/cuda/opr_cdtp.cu
- src/math/bcknd/device/cuda/opr_conv1.cu
- src/math/bcknd/device/cuda/opr_dudxyz.cu
- src/math/bcknd/device/cuda/opr_opgrad.cu
- src/math/bcknd/device/hip/ax_helm.hip
- src/math/bcknd/device/hip/opr_cdtp.hip
- src/math/bcknd/device/hip/opr_conv1.hip
- src/math/bcknd/device/hip/opr_dudxyz.hip
- src/math/bcknd/device/hip/opr_opgrad.hip
- Throw a hard error for unsupported values of lx in the CUDA backend
-  Throw a hard error for unsupported values of lx in the HIP backend
>  Throw a hard error for unsupported values of lx in the CUDA/HIP backend

- src/.depends
- src/Makefile.am
- src/case.f90
- src/fluid/bcknd/cpu/fluid_abbdf_cpu.f90
- src/fluid/bcknd/cpu/pnpn_res_cpu.f90
- src/fluid/bcknd/device/device_fluid_plan4.f90
- src/fluid/bcknd/sx/pnpn_res_sx.f90
- src/fluid/fluid_abbdf.f90
- src/fluid/fluid_abbdf_fctry.f90
- src/fluid/fluid_aux.f90
- src/fluid/fluid_plan4.f90
- src/fluid/fluid_pnpn.f90
- src/fluid/pnpn_res.f90
- src/fluid/pnpn_res_fctry.f90
- Move step info into common aux module
- CPU version of new (even more) modular solver
> CPU version of the new (even more) modular solver

- src/.depends
- src/math/bcknd/device/tensor_device.F90
- Remove unnecessary dep on comm
- Update deps
> Quality of life fixes

- src/adt/htable.f90
- src/adt/uset.f90
- src/mesh/mesh.f90
> Fix runtime issues caused by flaky LLVM based compilers

- src/bc/bcknd/device/cuda/facet_normal_kernel.h
- src/bc/bcknd/device/hip/facet_normal_kernel.h
- src/bc/bcknd/device/opencl/facet_normal_kernel.cl
- src/common/utils.f90
- src/fluid/fluid_method.f90
- src/io/nmsh_file.f90
- src/io/re2_file.f90
- src/krylov/pc_hsmg.f90
- src/mesh/mesh.f90
- src/sem/coef.f90
Adds initial support for outlet normal and fixes bugs with facet_normal
> Add bc outlet normal and fix bc bugs

- src/.depends
- src/Makefile.am
- src/device/opencl/prgm_lib.F90
- src/device/opencl/prgm_lib.h
- src/krylov/pc_hsmg.f90
- src/math/bcknd/device/cuda/schwarz.cu
- src/math/bcknd/device/device_schwarz.F90
- src/math/bcknd/device/hip/schwarz.hip
- src/math/bcknd/device/opencl/fdm_kernel.cl
- src/math/bcknd/device/opencl/schwarz.c
- src/math/bcknd/device/opencl/schwarz_kernel.cl
- src/math/fdm.f90
- src/math/schwarz.f90
- Cleanup
- Add OpenCL kernels for schwarz
> Add OpenCL kernels for schwarz

- src/.depends
- src/Makefile.am
- src/bc/non_normal.f90
- src/fluid/fluid_method.f90
- src/fluid/fluid_pnpn.f90
Adds support for bc ON, properly.
> Non normal bc

- makeneko.in
> Exit makeneko non-zero if compilation failed

- reframe/checks.py
- reframe/get-tgv-dns.sh
- reframe/minihemi.case.template
- reframe/rocm-select-gpu
- reframe/settings.py
- reframe/tgv.case.template
TODO: add settings for relevant systems, make dt a bit less hacky, fix reference values
> WIP: Add reframe test suite

- doc/pages/case-file.md
- src/bc/bc.f90
- src/comm/mpi_types.f90
- src/common/parameters.f90
- src/fluid/fluid_method.f90
- src/fluid/fluid_pnpn.f90
- src/io/nmsh_file.f90
- src/io/re2_file.f90
- src/krylov/pc_hsmg.f90
- src/mesh/mesh.f90
Adds support to choose bcs in the parameter file. A rather large revamp of how we treat facets and bcs.
> Labeled facet

- src/case.f90
- src/common/source.f90
- src/common/user_intf.f90
- src/fluid/fluid_method.f90
- src/math/math.f90
Adds support for the user to define a "vector valued" source term. This greatly helps when working with accelerators.
Also adds sort
> Improvements to the source term

- src/.depends
- src/Makefile.am
- src/gs/gather_scatter.f90
- src/gs/gs_comm.f90
- src/gs/gs_mpi.f90
This allows for selecting a communication method at runtime, similar to the backend
> Make communication method in gs abstract

- bench/tgv32/tgv.case
- examples/tgv/tgv.case
- src/comm/mpi_types.f90
- src/common/parameters.f90
- src/fluid/fluid_plan4.f90
- src/fluid/fluid_pnpn.f90
- src/mesh/mesh.f90
Adds support for projection for velocity. chagnes the name of proj_dim to proj_prs_dim and proj_vel_dim respectively.
> Velocity projection

- src/gs/bcknd/device/cuda/gs.cu
- src/gs/bcknd/device/cuda/gs_kernels.h
- src/gs/bcknd/device/gs_device_mpi.F90
- src/gs/bcknd/device/hip/gs.hip
- src/gs/bcknd/device/hip/gs_kernels.h
> Revert "Improve utilization in gs_pack_kernel"

- src/.depends
- src/common/checkpoint.f90
- src/io/chkp_output.f90
- src/simulation.f90
Add hooks to sync host/device during checkpoint write/read (save/restart)
> Fix chkp restart with device backend

- src/.depends
- src/adt/htable.f90
- src/adt/stack.f90
- src/adt/uset.f90
- src/comm/parmetis.F90
- src/common/parameters.f90
- src/config/num_types.f90.in
- src/device/device.F90
- src/device/opencl_intf.F90
- src/gs/gather_scatter.f90
- src/io/chkp_file.f90
- src/io/fld_file.f90
- src/math/schwarz.f90
- src/mesh/mesh.f90
- src/sem/dofmap.f90
- tests/htable/htable_i4.pf
- tests/htable/htable_i4t2.pf
- tests/htable/htable_i4t4.pf
- tests/htable/htable_i8.pf
- tests/htable/htable_pt.pf
- tests/htable/htable_r8.pf
- tests/stack/stack_i8.pf
- tests/uset/uset_i8.pf
Backport of #471 to legacy branch ( #464 )
> Define integer type in num_types

- src/neko.f90
Backport to legacy branch ( #464 )
> Don't assume real kind is related to byte size

- src/adt/uset.f90
- src/bc/bc.f90
- src/bc/symmetry.f90
- src/case.f90
- src/driver.f90
- src/fluid/advection.f90
- src/fluid/fluid_method.f90
- src/fluid/fluid_plan1.f90
- src/fluid/fluid_plan4.f90
- src/fluid/fluid_pnpn.f90
- src/gs/gather_scatter.f90
- src/krylov/bcknd/cpu/cg.f90
- src/krylov/krylov.f90
- src/krylov/krylov_fctry.f90
- src/krylov/pc_hsmg.f90
- src/krylov/precon_fctry.f90
- src/math/schwarz.f90
- src/mesh/mesh.f90
- src/neko.f90
- src/sem/interpolation.f90
Enough fixed pointers such that the solver can run with full diagnostics (-C=dangling) NAG Fortran <3
Fixes, #478
> Fix dangling pointers throughout the solver stack

- src/adt/stack.f90
- src/adt/tuple.f90
- tests/Makefile.am
- tests/stack/Makefile.in
- tests/stack/stack_2i4r8t3.pf
- tests/tuple/tuple.pf
- Add mixed (2xi4, r8) tuple, e.g. matrix entry (r,c,v)
- Add stack imp. for 2i4r8 3-tuple
> Add mixed (2xi4, r8) tuple, e.g. matrix entry (r,c,v)

- src/.depends_device
- src/Makefile.am
- src/device/opencl/prgm_lib.F90
- src/device/opencl/prgm_lib.h
- src/math/bcknd/cpu/opr_cpu.f90
- src/math/bcknd/device/cuda/cfl_kernel.h
- src/math/bcknd/device/cuda/opr_cfl.cu
- src/math/bcknd/device/hip/cfl_kernel.h
- src/math/bcknd/device/hip/opr_cfl.hip
- src/math/bcknd/device/opencl/cfl_kernel.cl
- src/math/bcknd/device/opencl/opr_cfl.c
- src/math/bcknd/device/opr_device.F90
- src/math/operators.f90
- Move CPU based CFL calculation into backend foldeR
- Add CUDA kernel for computing CFL
- Add HIP kernel for CFL calculation
> Ensure CFL calculation is done on selected backend

- src/.depends
- src/Makefile.am
- src/math/bcknd/sx/opr_sx.f90
- src/math/bcknd/sx/sx_cfl.f90
- src/math/operators.f90
- Increase vector length during CFL calculation on SX
- Update deps.
> Increase vector length during CFL calculation on SX

- doc/pages/code-style.md
- Add an initial code style to the online documentation
- Minor fixes
> Add code style guideline to doxygen documentation

- examples/tgv/tgv.f90
- src/.depends
- src/Makefile.am
- src/sem/cpr.f90
Added module to: 
- Create spectral transformation matrices.
- Transform field to physical and spectral space.
- Truncate low energy Legendre coefficients.
Features missing:
- Output reconstructed files.
- Data redistribution when reading files with a different number of ranks than written.
- Input parameters in the .case file.
- Control subroutine that checks input parameters.
> data compression development

- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/cuda/math_kernel.h
- src/math/bcknd/device/device_math.F90
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/hip/math_kernel.h
- src/math/bcknd/device/opencl/math.c
- src/math/bcknd/device/opencl/math_kernel.cl
- tests/device_math/device_math_parallel.pf
- Add naive CUDA kernel for glsum
- Add naive HIP kernel for glsum
- Comments
- Add naive OpenCL for glsum and a glsum unit tests for all device backends
> Add device glsum

- src/sem/bcknd/device/cuda/coef_kernel.h
- src/sem/bcknd/device/hip/coef_kernel.h
Address the indicies issue raised in #504
> Fix invalid indicies

- src/gs/gather_scatter.f90
This PR fixes a bug in find_blks for corner cases when a rank does not have any shared faces and some other conditions were true. This bug has lead to issues during hsmg init depending on the number of ranks and geometry of the mesh, especially for lx=2.
This fix should resolve a lot of issues related to different behaviors depending on the number of ranks.
> Fix find_blks

- src/io/file.f90
Help CCE to figure out the class type, fixes #541
> Explicitly figure out the class family

- configure.ac
- m4/ax_darshan.m4
Add option during configuration to link Neko to Darshan for I/O profiling.
> Add scripts to link Neko with Darshan profiler

- src/.depends
- src/Makefile.am
- src/comm/mpi_types.f90
- src/io/file.f90
- src/io/format/stl.f90
- src/io/stl_file.f90
- src/mesh/tet_mesh.f90
- src/mesh/tri_mesh.f90
- Make tet mesh private
- Add triangle surface mesh and stl reader
> Support for reading STL files

- src/.depends
- src/io/stl_file.f90
- src/io/vtk_file.f90
- src/mesh/tri_mesh.f90
- Add a fake 'id' for each point
- Make mesh info (nelv, mpts) public
- Add support to write a triangulated surface as a VTK file
> Support for writing triangulated surfaces as VTK files

- src/.depends
- src/Makefile.am
- src/fluid/fluid_abbdf_fctry.f90
- src/fluid/fluid_pnpn.f90
- src/fluid/fluid_volflow.f90
Fixes #553
- Add volflow formulation for pnpn solver
- Throw an error if vol flow is used with a device backend
> Add volflow for fluid_pnpn

- src/.depends
- src/fluid/fluid_pnpn.f90
- src/fluid/fluid_volflow.f90
Fixes #554 (only for `fluid_pnpn`)
> Add support for device backend in volflow

- configure.ac
- src/krylov/bcknd/device/pipecg_device.F90
Minor bug fix in device pipelined CG.
> NEKO v0.4.2

- .github/workflows/develop.yml
- .github/workflows/main.yml
- configure.ac
- m4/ax_cray.m4
- src/comm/redist.f90
- src/common/sampler.f90
- src/device/hip_intf.F90
Fix bug in redistribution routine
> NEKO v0.4.3

- src/adt/htable.f90
The fix will trigger a table growth faster, and hopefully reduce init. time for larger problems.
> Adjust htable growth factor

- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/opencl/math.c
Updated sizes of saved buffer check for glsc3_many
> fixed sizes in glsc3_many

- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/opencl/math.c
- Reduce cudamalloc calls during reductions
- Reduce hipmalloc calls during reductions
- Reduce clcreatebuffer calls during reductions
> Reduce malloc/free calls during reductions (device)

- src/krylov/bcknd/device/cuda/gmres_aux.cu
- src/krylov/bcknd/device/hip/gmres_aux.hip
> Change to pinned memory for red. buffers in gmres

- m4/ax_adios.m4
https://github.com/ExtremeFLOW/EuroHack22/issues/1
> Don't pollute Neko's preprocessor flags with ADIOS2's CXX flags

- configure.ac
- m4/ax_nccl.m4
Related to https://github.com/ExtremeFLOW/EuroHack22/issues/2
> Add hooks to link against NCCL 

- src/math/mathops.f90
> fixed some inconsistencies in doxygen for mathops

- examples/tgv/tgv.case
- examples/tgv/tgv.f90
make the tgv example a bit more verbose and removing inconsistencies.
> updates to tgv example

- src/math/bcknd/device/cuda/math_kernel.h
Ref: https://github.com/ExtremeFLOW/EuroHack22/issues/3
> Transpose glsc3_many kernel, improving memory traffic

- src/simulation.f90
partially addressing discussion #497. Just adding a sampler before the time loop.
> added correct sampling at initial time

- examples/lid/README.md
- examples/tgv/README.md
> added readme files

- src/simulation.f90
added section headings and reordered the postprocessing a bit.
> reordered the postproc

- src/io/nmsh_file.f90
- src/io/re2_file.f90
- src/io/rea_file.f90
- src/io/vtk_file.f90
- src/mesh/hex.f90
- src/mesh/mesh.f90
- src/mesh/quad.f90
- src/sem/dofmap.f90
> Revert "Revert "Consitent symmetric vertex notation""

- src/gs/gather_scatter.f90
**Note:** This only affects the reported number of per PE internal dofs, not the actual simulation.
> Fix overflow in reported avg. internal gs for large problems

- src/adt/htable.f90
Change to quadratic probing to reduce clustering in hash tables
> Change probing method in hash table

- .github/workflows/develop.yml
- .github/workflows/main.yml
- reframe/checks.py
- reframe/settings.py
- reframe/src/tgv.case.template
Add a ReFrame based regression test step after build and unit tests has passed
> Add ReFrame tests to integration tests

- .github/workflows/develop.yml
- .github/workflows/main.yml
- reframe/checks.py
- reframe/src/rayleigh.case.template
- reframe/src/rayleigh.f90
- Add mini rayleigh-benard to reframe checks
- Add Rayleigh-benard smoke test to ReFrame stage
> Test scalar features in CI

- .github/workflows/develop.yml
- reframe/checks.py
- reframe/settings.py
- Clamp small RB case to 2 tasks
- Update develop.yml
- Update develop.yml
- Use correct settings for gh actions
- Reenable deps
> Fix reframe tests for rayleigh-benard

- src/io/nmsh_file.f90
- src/io/re2_file.f90
This fixes issues with generating nmsh files for meshes with more than 8 or 9 Million elements.
> Larger mesh support

- contrib/prepart/prepart.f90
> Periodic BCs needs mesh connectivity

- doc/pages/appendix.md
- src/common/log.f90
Add support for various level of log verbosity, e.g. to allow for debug messages.
> Add log verbosity level

- contrib/prepart/prepart.f90
Fixed regression in offline load-balancing tool for periodic boundary conditions
> Fixed regression in offline tool

- src/gs/gather_scatter.f90
- src/mesh/mesh.f90
- Reduce comm. during mesh init
- Fix invalid data type
- Reduce comm. during gs init
- Build neigh. order list
> Reduce comm. during init

- configure.ac
- src/Makefile.am
- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/cuda/opr_cfl.cu
- src/math/bcknd/device/device_math.F90
- src/math/bcknd/device/device_mpi_reduce.c
- src/math/bcknd/device/device_mpi_reduce.h
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/hip/opr_cfl.hip
- src/math/operators.f90
- Start reductions from dev. memory if dev. MPI is present (CUDA)
- Start reductions from dev. memory if dev. MPI is present (HIP)
> Remove redudant memory copies in reductions (if dev. MPI is present)

- .github/workflows/develop.yml
> Fix issues with gh actions macOS runners

- src/common/sampler.f90
Add profiler flags to sampler as it takes significant time on the time-steps it runs.
> added NVTX flags to sampler

- doc/pages/appendix.md
- src/gs/gather_scatter.f90
- Add the posibility to fix the device MPI gs sync strategy via env. var
- Remove init. data transfer from measurements
> Various device MPI improvements and fixes for GS auto-tuning

- src/math/bcknd/device/opencl/fdm.c
- src/math/bcknd/device/opencl/fdm_kernel.cl
Backport CUDA/HIP opt. descr. in  #724
> Backport shm mem opt in OpenCL fdm

- patches/nvhpc_bge.patch
- src/common/jobctrl.f90
- src/common/signal.f90
- Fix invalid sighdl call
- Add SIGUSR1 to joblimit
> Fix SIGUSR and joblimit

- src/fluid/advection.f90
- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/cuda/math_kernel.h
- src/math/bcknd/device/device_math.F90
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/hip/math_kernel.h
- src/math/bcknd/device/opencl/math.c
- src/math/bcknd/device/opencl/math_kernel.cl
- Add HIP kernel for vdot
- Add CUDA kernel for vdot
- Add OpenCL kernel for vdot
- Change to vdot3, reducing function calls/kernel launches
> Device vdot3

- .gitignore
See issue #765 we could perhaps add more stuff. But this already reduces from 600+ files to about 40.
> Add minimalistic gitignore

- src/math/bcknd/device/cuda/schwarz.cu
- src/math/bcknd/device/cuda/schwarz_kernel.h
This worked well for CUDA, but on the HIP side it was a LOT worse. 
Not sure why the HIP side was worse.
> optimised schwarz extrude for CUDA

- src/io/re2_file.f90
> Add small nelv guards in re2 file reader

- src/math/bcknd/device/hip/ax_helm_kernel.h
This fixes gives up to 40% improvments depending on poly. order
> Improve Ax helm perf on MI250X

- src/math/bcknd/device/cuda/cdtp_kernel.h
- src/math/bcknd/device/cuda/conv1_kernel.h
- src/math/bcknd/device/cuda/dudxyz_kernel.h
- src/math/bcknd/device/cuda/opgrad_kernel.h
- src/math/bcknd/device/cuda/opr_cdtp.cu
- src/math/bcknd/device/cuda/opr_conv1.cu
- src/math/bcknd/device/cuda/opr_dudxyz.cu
- src/math/bcknd/device/cuda/opr_opgrad.cu
- src/math/bcknd/device/hip/cdtp_kernel.h
- src/math/bcknd/device/hip/conv1_kernel.h
- src/math/bcknd/device/hip/dudxyz_kernel.h
- src/math/bcknd/device/hip/opgrad_kernel.h
- src/math/bcknd/device/hip/opr_cdtp.hip
- src/math/bcknd/device/hip/opr_conv1.hip
- src/math/bcknd/device/hip/opr_dudxyz.hip
- src/math/bcknd/device/hip/opr_opgrad.hip
Add kstep version of CUDA/HIP kernels together with autotuning between 1D and KSTEP.
> Add kstep version of CUDA/HIP kernels

- examples/rayleigh-benard/rayleigh.f90
- examples/turbpipe/pipe.f90
- reframe/src/rayleigh.f90
- src/common/source.f90
- src/common/user_intf.f90
- src/fluid/bcknd/device/device_fluid_plan4.f90
- src/fluid/fluid_plan4.f90
- src/fluid/fluid_pnpn.f90
- src/scalar/scalar_pnpn.f90
- src/scalar/source_scalar.f90
- Make fluid source term time-dependent (optional)
- Make scalar source terms time-dependent (optional)
> Time-dependent source terms

- src/fluid/pnpn_res.f90
- src/math/math.f90
- src/math/mathops.f90
- src/math/operators.f90
- src/sem/coef.f90
Just small stuff added during the day, no additional functionality here.
> Misc docs/comments

- src/device/cuda_intf.F90
- src/device/device.F90
- src/device/hip_intf.F90
- src/gs/bcknd/device/gs_device.F90
- src/gs/bcknd/device/gs_device_mpi.F90
- src/gs/gather_scatter.f90
- src/gs/gs_bcknd.f90
- src/gs/gs_comm.f90
- src/gs/gs_mpi.f90
- Add async. event based gs
- Move event record
- change to streamwait
- Fix race
- Cleanup
> Async. gather-scatter 

- .github/workflows/main.yml
Here is an attempt, but not sure if this is correct.
> Add Github action to upload test results

- m4/ax_cuda.m4
- m4/ax_nvtx.m4
- Fix cflags bug
- Fix cflags bug
> Fix invalid CFLAGS for NVCC

- src/math/operators.f90
Starting to cherry-pick some stuff added during the scalar dealiasing work.
> Add a docstring for conv1

- configure.ac
- src/.depends
- src/Makefile.am
- src/common/cpuid.c
- src/common/system.f90
- src/neko.f90
If supported by the platform, retrieve and output CPU type at job start
> Output CPU type

- .gitignore
It's the applications that were added for the statistics.
> Add new contrib executables to gitignore

- src/case.f90
- src/common/statistics.f90
Only output statistics information if there are quantities, fixes #851
> Fix statistics output

- src/common/sampler.f90
- src/simulation.f90
Check if data is to be written, and only output info if true, fixes #853
> Only output to log if a data is written

- doc/pages/case-file.md
Add missing stats parameters to doxygen documentation, fixes #852
> Add missing stats params to documentation

- examples/rayleigh-benard-cylinder/README.md
- examples/rayleigh-benard-cylinder/rayleigh.case
- examples/rayleigh-benard-cylinder/rayleigh.f90
- examples/rayleigh-benard/rayleigh.case
- examples/rayleigh-benard/rayleigh.f90
- src/bc/bcknd/device/cuda/inhom_dirichlet.cu
- src/bc/bcknd/device/cuda/inhom_dirichlet_kernel.h
- src/bc/bcknd/device/device_inhom_dirichlet.F90
- src/bc/bcknd/device/hip/inhom_dirichlet.hip
- src/bc/bcknd/device/hip/inhom_dirichlet_kernel.h
- src/bc/bcknd/device/opencl/inhom_dirichlet.c
- src/bc/bcknd/device/opencl/inhom_dirichlet_kernel.cl
- src/bc/usr_inflow.f90
- src/case.f90
- src/common/user_intf.f90
- src/scalar/scalar_pnpn.f90
- src/scalar/scalar_scheme.f90
Small RBC cylinder case with 600 elements.
> RBC cylinder example

- examples/lid/lid2d.f90
> Fix user code in the lid2d example

- src/device/device.F90
- src/device/opencl_intf.F90
This add the missing equiv. stream/event routines from CUDA/HIP in the OpenCL interface
> Add missing OpenCL features for "stream/events"

- src/bc/bc.f90
As the title says. Only adds doxygen comments.
> Improve docs for bc_t

- src/math/fdm.f90
- src/math/schwarz.f90
This refers to the issue raised in ref #795
> Make fdm private

- src/math/fast3d.f90
Just a quick documentation fix for `setup_intp`
> Edit documentation in fast3d

- src/krylov/bcknd/device/pipecg_device.F90
Leak and redundant device allocation of `alpha` and `beta` in each solve step
> Fix memory leak in device pipelined CG

- src/math/fast3d.f90
- src/sem/dofmap.f90
- src/sem/space.f90
- src/sem/speclib.f90
* As the subject says
* Provisionally "upgraded" the docstring to our format for one of the routines in speclib. Or is the idea not to touch it? It is a bit said that it is not in doxygen.
> Misc additions to docstrings

- src/case.f90
Allow for a case to be created from either a JSON file, or an already loaded JSON object. The intent is to allow for programatic case creation from e.g. pyneko or future endeavours
> Change case init to allow for either a file or a json object

- .github/workflows/develop.yml
- Update to latest nvhpc
- Fix cuda path
> Update GitHub Actions to latest nvhpc

- contrib/average_field_in_space/average_field_in_space.f90
- contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
- src/bc/dong_outflow.f90
- src/fluid/advection.f90
- src/fluid/fluid_plan1.f90
- src/fluid/fluid_scheme.f90
- src/krylov/pc_hsmg.f90
- src/sem/coef.f90
- tests/point_interpolation/point_interpolation_parallel.pf
Encapsulate all coef routines as type bound preocedures, following #974, #973, #795 and #794
> Make coef private, with type-bound procedures

- doc/Doxyfile.in
- doc/Makefile.am
- doc/pages/dev_patterns.md
- doc/pages/index.md
This has everything discussed in the dev meetings, as far as I could remember. Also, quite a bit of points, which just put down as a rule something already followed in the code. Plus some additional points from myself, up for discussion.
> A draft for programming conventions and patterns

- src/io/re2_file.f90
This version of re2 was introduced into Nek5000 in September 2023.
Header format of the re2 file was changed in version 4. Updates have been made to re2_file.f90 to support the new header in addition to the old.
Additionally added support for EXO boundary types. This allows "sidesets" from exodus to be used for setting boundary conditions in the case files.
> Updated re2 file reader to support version 4.

- examples/tgv/tgv.case
Update the tgv.case file to correct for Neko input parsing changes.
> tgv case fix

- bench/tgv32/tgv.case
- bench/tgv32/tgv.f90
Needed for DEEP-SEA Jube script wich depends on develop
> Fix tgv bench

- doc/pages/installation.md
> Add instructions to run Neko using the Docker container

- doc/pages/installation.md
> Add ParMETIS instructions

- doc/pages/installation.md
> Add instructions for building from source

- src/math/bcknd/device/opencl/tensor.c
- src/math/bcknd/device/opencl/tensor_kernel.cl
- src/math/bcknd/device/tensor_device.F90
> Add OpenCL kernel for tensor el list

- src/mesh/point_zone.f90
Resolving issue #1034 
Added null pointer assignment as suggested by @njansson
> Added missing null_ptr assignment

- src/common/projection.f90
This adds the fix from #776, which was merged into the release branches, but never made it back into develop.
> Backport projection fix from releases

- src/mesh/tri.f90
(cherry picked from commit c80fa2d25a503e7bf865f69c3028cca95e993962)
> Fix invalid access in centroid calculation

- src/case.f90
- src/common/checkpoint.f90
- src/fluid/bcknd/device/pnpn_res_device.F90
- src/fluid/fluid_pnpn.f90
- src/fluid/fluid_scheme.f90
- src/io/chkp_file.f90
- src/scalar/scalar_pnpn.f90
- src/scalar/scalar_scheme.f90
- src/simulation.f90
This backports the restart fixes in #1047 to the current `release/0.7` branch
> Backport restart fixes to 0.7 release branch

- src/device/device.F90
- src/device/opencl_intf.F90
> Replace deprecated OpenCL call (clEnqueueMarker)

- src/device/device.F90
Just looking through the code; not related to any observed bug.
> OpenCL: A trivial fix for error checking

- .github/workflows/develop.yml
We should really change to spack...
> CI fixes for horrible homebrew

- src/io/rea_file.f90
Just added the 'm' curvature type case in the rea file to match with what is done in `re2_file.f90`.
> Add 'm' curvature type to rea_file

- .github/workflows/develop.yml
- Makefile.am
> Fix missing nvhpc patch from dist target

- src/adt/stack.f90
Added function to check if stack is empty
> Slight addition to stack

- doc/Doxyfile.in
- doc/pages/io.md
Inspired by the recent GH Discussion. Adds some information on how to produce a mesh, the .fld format and checkpoints.
> Add basic documenation on IO file formats

- src/.depends
- src/io/chkp_file.f90
- src/io/csv_file.f90
- src/io/file.f90
- src/io/fld_file.f90
- src/io/generic_file.f90
- src/io/map_file.f90
- src/io/nmsh_file.f90
- src/io/re2_file.f90
- src/io/rea_file.f90
- src/io/stl_file.f90
- src/io/vtk_file.f90
Ensure calls to file readers actually check if the file they are supposed to read exists.
> Check if the file exists

- src/case.f90
- src/mesh/point_zone_registry.f90
Point zones are now initialized before the physics. This opens the door for zone wise material parameters, source terms etc.
> Updated point zone initialization

- src/math/operators.f90
The if-else block prevented vectorisation of the loop over xyz. By replacing the logical block with a msk, the entire xyz vectorises fine.
> Remove if-else block to ease vectorisation

- src/common/projection.f90
Only fixes so the log is more correct.
> Fix so same residual is output in projection as ksp_monitor

- .github/workflows/develop.yml
> Update for new gh actions

- doc/pages/case-file.md
Just list the number -> type association in the .fld produced by output_boundary.
> Add doc for output_boundary

- src/fluid/fluid_pnpn.f90
- src/scalar/scalar_pnpn.f90
debug projection to make simulation work without projection and remove some dummy stuffs
> debug on projection

- doc/pages/simcomps.md
- src/simulation_components/probes.F90
This pull request introduces a probe header that contains the number of probes, number of fields, and a list of the fields probed in order. 
It also updates the documentation of probes to include the output format of the probed information.
> Introduce probe header and update probe documentation

- doc/pages/case-file.md
- doc/pages/user-file.md
> reformat links for doxygen

- src/io/file.f90
- src/io/generic_file.f90
> Add marker for serial files, and fix deadlock

- src/.depends
- src/Makefile.am
- src/les/bcknd/cpu/smagorinsky_cpu.f90
- src/les/bcknd/cpu/vreman_cpu.f90
- src/les/les_model_fctry.f90
- src/les/smagorinsky.f90
- src/wall_models/wall_model_fctry.f90
Classical Smagorinsky model is added.
> Feature/stress formulation, smagorinsky model

- src/.depends
- src/math/operators.f90
Adds a strong gradient and a divergence operator. Both are wrappers around calls to dudxyz. Further optimizations (I guess mostly for the device) can be done in the future if necessary.
> Add div and grad operators

- Makefile.am
- configure.ac
> Add missing logic for

- src/les/bcknd/cpu/sigma_cpu.f90
Sorry, I messed up the order of pushing a commit and resolving a review comment, so the SGS models got automerged before I added these spaces.
> Add spaces in sigma model code

- .github/actions/setup_json-fortran/action.yml
- .github/actions/setup_json-fortran/readme.md
- .github/actions/setup_pfunit/action.yml
- .github/actions/setup_pfunit/readme.md
- .github/workflows/check_gnu.yml
- .github/workflows/check_lint.yml
- .github/workflows/check_reframe.yml
- .github/workflows/develop.yml
- .github/workflows/main.yml
This pull request updates the error handling of actions to improve the overall reliability and stability of the code. The changes include better error messages and improved error handling logic.
Please do not manually merge this PR. Update the following repository level changes on github:
- Branch requirements should be assigned to the completion step for both main and develop.
- The completion job should be the only requirement set `develop / Develop PR Ready` since that job checks all the others. This allow us to extend the CI pipeline later, without modifying the branch protection rules.
EDIT: The previously mentioned repository variables does not support PR's submitted from forks. Those should be removed again.
Depends on #1303
> Update error handling of actions

- .github/workflows/main.yml
The modernized main CI had some bugs related to which compiler was used and how this was communicated to the json-fortran action.
> Fix modernized main CI

- doc/pages/user-guide/simcomps.md
- src/simulation_components/probes.F90
As the title says, there was a bug causing probes to not work when using other the new inputs like `line`, `circle`, etc.
> Fix bug in probes and wrong documentation

- doc/pages/developer-guide/code-style.md
These commands worked for me. Thought adding them would make it easier for people to check their stuff locally.
> Added command to install flint and execute it

- .github/workflows/develop.yml
This pull request optimizes the execution of the linter by running it in parallel, which helps to avoid development slowdowns.
> Optimize linter execution

- src/.depends
- src/bc/non_normal.f90
- src/bc/symmetry.f90
- src/fluid/fluid_user_source_term.f90
- src/fluid/fluid_volflow.f90
- src/io/stl_file.f90
- src/mesh/tri_mesh.f90
- src/scalar/scalar_source_term.f90
- src/scalar/scalar_user_source_term.f90
- src/simulation_components/probes.F90
- src/source_terms/boussinesq_source_term.f90
- src/source_terms/brinkman_source_term.f90
- src/source_terms/const_source_term.f90
- src/source_terms/source_term.f90
A couple of dangling pointers found by NAG Fortran
> Fixed dangling pointers

- src/fluid/fluid_scheme.f90
Adds and expands the values output in the bdry file and provides their meaning in the log file. 
Helps a lot when setting up a case and troubleshooting.
> Add info of meaning of values in bdry file

- src/common/profiler.F90
- src/fluid/fluid_pnpn.f90
- src/gs/gather_scatter.f90
- src/krylov/pc_hsmg.f90
- src/scalar/scalar_pnpn.f90
- **Rename regions to support fjprof**
- **Add hooks to start/stop the advanced performance profiler**
> Add support for Fujitsu Advanced Performance Profiler

- src/common/json_utils.f90
- src/fluid/fluid_source_term.f90
This pull request adds a new extractor for JSON arrays based on name and index. It also updates the fluid source term to use this new extractor.
Additionally the JSON getters now look for a valid path before attempting to access the desired key.
> Add new JSON array extractor and use it in fluid source term

- src/math/bcknd/device/opencl/math_kernel.cl
- **Fix computation of enstrophy on device backends**
- **Fix invalid type in kernel argument**
> Fix invalid type in OpenCL argument

- doc/Makefile.am
- doc/pages/developer-guide.md
- doc/pages/developer-guide/important_types.md
If you think I missed an important one, please advise. Also if you think the desciption is bad.
> Add overview of the most important types to the docs

- m4/ax_blas.m4
- m4/ax_lapack.m4
Among other things, blas/lapack tuned for aarch64
https://developer.nvidia.com/nvpl
> Add support for NVIDIA Performance Library (NVPL)

- src/io/re2_file.f90
- src/sem/dofmap.f90
Rea2nbin segfaults for meshes with combination of labeled zones and periodic bcs. Also adds support for EXO labels in the mesh.
> Fix segfault for rea2nbin

- src/field/mean_field.f90
- src/fluid/fluid_stats.f90
- src/simulation_components/fluid_stats_simcomp.f90
Fixes some whitespace style and adds better docstrings.
> Style and doc update

- doc/pages/appendices.md
- src/common/json_utils.f90
- src/common/log.f90
- src/common/utils.f90
- src/neko.f90
This pull request includes several commits that add logging levels and improve error handling in the codebase. 
The commits introduce new function for logging, `log_header`, and update `neko_error` to output in stderr. Additionally, a new environment variable `NEKO_LOG_FILE` is introduced to specify the log file name, with `stdout` used as the default if not set. The pull request also includes documentation updates for the new variable.
Additionally the json utilities have been extended to handle extraction of entire sub structures.
> Add logging levels and improve error handling

- src/krylov/bcknd/cpu/cheby.f90
- src/krylov/bcknd/device/cheby_device.F90
Fix the sequence for the Chebyshev iteration.
> cheby: fix parameter sequence

- src/scalar/scalar_scheme.f90
Fixes json parsing in scalar material properties setter.
> Fix json parsing in scalar scheme

- src/simulation_components/lambda2.f90
Make init from attributes not depend on field registry.
> Improve init of lambda2

- contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90
- src/simulation.f90
Some small fixes, feel free to piggyback off of this to get some small changes in
- outputs the joblimit checkpoint in the output directory 
- Fixes the correct number of arguments in the postprocess_fluid_stats contrib script
> Some small fixes

- src/sem/speclib.f90
Quick check is to compare with PNLEG which also computes the Legendre polynomials in a point
> Fix legendre_poly

- src/simulation.f90
Fix potential access to unallocated memory.
Update of material properties expected cp and lambda from the scalar solver. However, C%scalar might not be allocated, causing an invalid access
> Fix invalid access to unallocated components of a case

- src/fluid/fluid_scheme.f90
I dunno, ran into segfaults locally and it smee ed to be relate dot the new bcs. I didnt have time to check it our properly, but perhaps Tim knows why this seems to fix the problem.
> Fixes segfault due to trying to apply wm%symmetry%bcX 

- src/multigrid/tree_amg_multigrid.f90
- src/multigrid/tree_amg_smoother.f90
- **Avoid implicit save attribute for constants**
- **Remove debug output**
- **Move output to Neko log**
> Cleanup AMG output

- src/comm/redist.f90
- src/mesh/mesh.f90
> Fix segfault in mesh redistribution

- src/fluid/fluid_pnpn.f90
- src/fluid/fluid_scheme.f90
- src/les/bcknd/cpu/dynamic_smagorinsky_cpu.f90
- src/les/bcknd/cpu/sigma_cpu.f90
- src/les/bcknd/cpu/smagorinsky_cpu.f90
- src/les/bcknd/cpu/vreman_cpu.f90
- src/les/bcknd/device/dynamic_smagorinsky_device.f90
- src/les/bcknd/device/sigma_device.f90
- src/les/bcknd/device/smagorinsky_device.f90
- src/les/bcknd/device/vreman_device.f90
move the extrapolated velocity to fluid_scheme, make the sgs model estimation based on the extrapolation
> change sgs estimation from uvw to uvw_e

- src/io/nmsh_file.f90
Bugfix, should be merged soon. Would be good to also check the rest of the file for similar bugs.
> Fix curve offset

- src/io/fld_file.f90
Should enable the new Nek5000 reader in Paraview to read our .fld files. Works with Paraview 5.13.2
> Remove "type: binary" from .nek5000

- src/bc/field_dirichlet.f90
- src/case.f90
- src/common/user_intf.f90
- src/fluid/bcknd/cpu/euler_res_cpu.f90
- src/fluid/flow_ic.f90
- src/fluid/fluid_plan1.f90
- src/fluid/fluid_scheme_base.f90
- src/fluid/fluid_scheme_compressible.f90
- src/fluid/fluid_source_term.f90
- src/simulation.f90
- src/time_schemes/runge_kutta_scheme.f90
- I accidentally resolved all the comments from @timfelle so that #1666 was automatically merged.
- Here is the fix commit to address comments from @timfelle for #1666
> Resolve comments from @timfelle for #1666

- src/gs/gather_scatter.f90
- src/gs/gs_comm.f90
- src/gs/gs_mpi.f90
Adds some comments in some of the gather scatter modules. Got inspired as I would like to use the gs_comm type for the communication in global_interpolation.
> Add comments in gather scatter

- src/adt/htable.f90
- src/case.f90
- src/io/fluid_output.f90
This pr fixes various issues observed with HPE Cray Compiling Environment (CCE) 18.x compilers (probably also applicable to other recent llvm based compilers). (closes #1694)
> Fix various issues with CCE 18.x

- tests/unit/gather_scatter/gather_scatter_parallel.pf
- Oops I did it again
- Here are some missing spacing/indentation fixes for #1704
> Fix spacing, indentation #1704

- README.md
update the description on how to compile json-fortran.
> updated compile instructions for json

- doc/pages/user-guide/statistics-guide.md
- src/simulation_components/fluid_stats_simcomp.f90
Naming of stats for 1D stats were incorrect and causaed a segfault after change last week. Lesson of the day/week: changing these things is really quite difficult.
> Fix documentation and behavior for 1D stats

- .github/workflows/check_format.yml
- contrib/lint_format/format.sh
- src/fluid/fluid_scheme_incompressible.f90
Ensure consistency in the script and CI configuration while demonstrating the default behavior of the script.
> Make formatting script and CI consistent with default behavior showcase

- src/scalar/scalar_scheme.f90
I think these guys were missed in PR#1771 :+1:
> Scalar bug fix

- src/math/matrix.f90
- src/math/vector.f90
to allow the size of vector with intent(in) to be retrieved.
> intent for vector and matrix getter functions

- examples/poisson/ax_poisson.f90
> Fix poisson example

- src/.depends
- src/bc/usr_inflow.f90
- src/bc/usr_scalar.f90
- src/math/schwarz.f90
This fixes an issue with device memory allocation for compilers not following a so-called "byte" scheme.
> Fixed device memory allocation

- src/fluid/fluid_base_fctry.f90
- src/io/file.f90
- src/krylov/krylov_fctry.f90
- src/krylov/precon_fctry.f90
- src/scalar/scalar_pnpn_bc_fctry.f90
- src/scalar/scalar_residual_fctry.f90
- src/source_terms/source_term_fctry.f90
- src/wall_models/wall_model_fctry.f90
I think I got all of them to use select case when it makes sense.
Also the manual construction of the error message with concat_string is now removed and using the neko type error instead.
> Cleanup our factories.

- src/math/field_math.f90
This matches the intent of `field_sub3` with that of `sub3`.
> correct intent of field_sub3

- src/bc/bcknd/device/device_inhom_dirichlet.F90
- src/bc/bcknd/device/device_neumann.F90
The title says it all.
This fixes a problem I had while running RBC on Lumi.
> Fix 0 block kernel launch for inhom dirichlet

- src/common/log.f90
- src/io/fld_file.f90
- src/io/map_file.f90
- src/io/re2_file.f90
- src/io/rea_file.f90
- src/io/vtk_file.f90
Refactor the code to replace manually assigned file units with the newunit feature, improving file handling consistency and reducing potential errors.
> Update file unit handling to use newunit

- src/.depends
- src/common/log.f90
- src/common/time_state.f90
- src/simulation.f90
- tests/regression/cylinder/ref1_dp.log
- tests/regression/cylinder/ref1_sp.log
- tests/regression/cylinder/ref2_dp.log
- tests/regression/cylinder/ref2_sp.log
- tests/regression/cylinder/test.sh
Enhance the logging of simulation time and status by moving the time status functionality to the time state module. Improve log formatting and ensure that simulation start messages accurately reflect any restarts. Clean up comments for better readability.
> Refactor time logging and simulation status updates

- src/math/vector.f90
Only works with -O2 or lower on LUMI still.
> Remove generic power and fix chsign

- doc/pages/user-guide/extension.md
- doc/pages/user-guide/io.md
- src/les/les_model_fctry.f90
- src/mesh/point_zone.f90
- src/mesh/point_zone_fctry.f90
- src/simulation_components/simulation_component_fctry.f90
- src/source_terms/source_term_fctry.f90
- src/wall_models/wall_model.f90
- src/wall_models/wall_model_fctry.f90
Adds the usual stuff to the factory and the base type.
> Add type injection to wall models and point zones

- src/math/bcknd/device/hip/hip_math.f90
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/hip/math_kernel.h
Introduce new device kernels for point-wise operations for the HIP backend.
> Add missing hip kernels

- src/krylov/pc_hsmg.f90
> Add monitor param for coarse grid

- doc/DoxygenLayout.xml
- doc/Makefile.am
- doc/pages/index.md
- doc/pages/user-guide.md
I think this is all what is needed to make it show up, right?
> Add missing documentation page to index

- src/case.f90
- src/io/chkp_output.f90
Another type with a = constructor.
> Fix checkpoint output constructor

- src/math/bcknd/device/cuda/cuda_math.f90
- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/cuda/math_kernel.h
- src/math/bcknd/device/device_math.F90
- src/math/bcknd/device/hip/hip_math.f90
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/hip/math_kernel.h
- src/math/bcknd/device/opencl/math.c
- src/math/bcknd/device/opencl/math_kernel.cl
- src/math/bcknd/device/opencl/opencl_math.f90
- src/math/field_math.f90
- src/math/math.f90
Introduce a normed difference operator for vector calculations and enhance absolute comparison functions to accept an optional tolerance value.
> Add normed difference operator and optional tolerance for comparisons

- examples/programming/custom_types.f90
- examples/programming/user_file_template.f90
- tests/integration/tests/test_examples/test_examples.py
Should hopefully force things staying in sync from now on.
> Fix programming examples, add their compilation to CI

- src/krylov/pc_hsmg.f90
This is essentially a forward port of #1932, but without the gs part (which was fixed in another PR)
> Fix bcs in HSMG that were not quite ok

- src/.depends
- src/Makefile.am
- src/bc/facet_normal.f90
- src/bc/field_dirichlet.f90
- src/bc/field_dirichlet_vector.f90
- src/common/mask.f90
- src/fluid/flow_ic.f90
- src/math/bcknd/device/cuda/cuda_math.f90
- src/math/bcknd/device/cuda/math.cu
- src/math/bcknd/device/cuda/math_kernel.h
- src/math/bcknd/device/device_math.F90
- src/math/bcknd/device/hip/hip_math.f90
- src/math/bcknd/device/hip/math.hip
- src/math/bcknd/device/hip/math_kernel.h
- src/math/bcknd/device/opencl/math.c
- src/math/bcknd/device/opencl/math_kernel.cl
- src/math/bcknd/device/opencl/opencl_math.f90
- src/math/field_math.f90
- src/math/math.f90
- src/mesh/point_zone.f90
- src/multigrid/tree_amg.f90
- src/neko.f90
- src/scalar/scalar_ic.f90
- src/simulation_components/force_torque.f90
- src/simulation_components/probes.F90
- src/source_terms/brinkman_source_term.f90
- src/wall_models/spalding.f90
Introduction of a mask type, which holds and manage host and device masks in their natural language.
Introduce it to Point zones to showcase the usage.
> Introduce a mask type

- examples/euler_2d_forward_facing_step/step.f90
- src/fluid/fluid_scheme_compressible_euler.f90
- BC updated reset
- IC for forward facing step example
> Fix BC, example for compressible module

- src/api/neko_api.f90
- src/python/pyneko/intf.py.in
> Fix invalid sp/dp assumption in API and pyneko code

- doc/pages/user-guide/io.md
Corrected output file description and added link to Nek5000 documentation
> Update of fluid output file documentation; fixes #1982

- .github/workflows/check_nvidia.yml
> Fix CI issues with nvhpc 25.9

- src/fluid/stress_formulation/bcknd/device/pnpn_res_stress_device.F90
- src/math/bcknd/device/ax_helm_full_device.F90
Regression introduced in #2124
> Fix missing symbols for builds without OpenCL
