src/common/sampler.f90
Currently, the sample timing only takes the time from rank zero. However, when other distributed storage mediums are used (e.g. local/shared burst buffers) the variance can be high, and rank zero may not be representative of the I/O time. This is also needed to prepare for a bandwidth calculation patch (i.e output both the sample time and I/O bandwidth) later.
- the log module records only messages from pe_rank zero
- use MPI_MAX to get the maximum sample time as overall output time
=> Output max sample time instead of rank zero time

src/fluid/bcknd/cpu/pnpn_res_cpu.f90, src/fluid/bcknd/device/pnpn_res_device.F90, src/fluid/bcknd/sx/pnpn_res_sx.f90, src/fluid/fluid_pnpn.f90, src/fluid/pnpn_res.f90
Adds the missing facet normal term to the rhs for symmetry boundary conditions. 
Seems to be an issue when two symmetry bcs intersect each other and are perpendicular (e.g. hemi).
=> Symmetry facet normal

src/math/bcknd/device/cuda/schwarz_kernel.h, src/math/bcknd/device/hip/schwarz_kernel.h
Seems there is something different between Nvidia/AMD with regards to in what order operations are performed within a threadblock.
=> Fix possible race

src/common/utils.f90, src/mesh/mesh.f90, src/sem/dofmap.f90
Lets the user define a deformation subroutine that is then applied to the generated dofs in dofmap. 
I feel like this slaughters a few kittens and we should probably add checks and prints when this function is called.
=> User deform mesh

src/fluid/fluid_method.f90, src/fluid/fluid_pnpn.f90
Increases readability, does not impose the specified velocity bc at the ON boundary. Should enable the flow to flow out easier, but from my measurements seems to make 0 difference, another difference is that ON does not take a time dependent inflow into account. Regarding the time dependence we should maybe consider how we want to do with the ON bc.
ON will still not work with tripping close to the boundary since applying zero velocity in the non-normal direction is unphysical when the turbulence hits the ON boundary.
=> Make application of vel bc more reasonable

src/gs/bcknd/device/gs_device_mpi.F90
Without this change, the pressure start residual is sometimes wrong (and maybe other things too), probably due to a race condition. This seems to happen maybe once per run of Tgv32 with 2 ranks. Sometimes it causes divergence, sometimes just a few more pressure iterations.
Adding this sync makes my test case completely deterministic. Over four Tgv32 runs the residuals and iteration counts for the complete run are exactly the same.
=> Add sync in device MPI nbwait

doc/Doxyfile.in
Don't run preprocessing when building the documentation, such that all possible backends are extracted
=> Disable preprocessing in doxygen

src/common/projection.f90, src/fluid/fluid_method.f90, src/gs/bcknd/device/gs_device_mpi.F90
- Remove uncessary casts
- Don't assume rp corresponds to byte size
=> Don't assume rp corresponds to byte size

src/.depends, src/.depends_device, src/Makefile.am, src/device/opencl/prgm_lib.F90, src/device/opencl/prgm_lib.h, src/math/bcknd/device/cuda/math_kernel.h, src/math/bcknd/device/hip/math_kernel.h, src/sem/bcknd/device/cuda/coef.cu, src/sem/bcknd/device/cuda/coef_kernel.h, src/sem/bcknd/device/device_coef.F90, src/sem/bcknd/device/hip/coef.hip, src/sem/bcknd/device/hip/coef_kernel.h, src/sem/bcknd/device/opencl/coef.c, src/sem/bcknd/device/opencl/coef_kernel.cl, src/sem/coef.f90, src/sem/dofmap.f90
- CUDA kernels for computing geometric factors on device
- Add HIP kernel for geometric factors
- Add OpenCL kernel for geometric factors
- Map dof coords. to device
- Add CUDA kernel for dxyzdrst computation
- add missing copy
- Add missing kernels in DIST target
- Fix and add missing OpenCL kernels for device coef
- Fix ambigous use of '1.0'
- Update HIP kernels for coef
- Fix horrible bugs...
=> Offload (most of) coef. calc. to device

src/sem/coef.f90
Temporarily disable dxyzdrst coef calculations using HIP due to instabilities (...:bug:...)
=> Temp. disable HIP backend for dxyzdrst kernel

src/gs/bcknd/cpu/gs_cpu.f90, src/gs/bcknd/device/gs_device.F90, src/gs/bcknd/sx/gs_sx.f90, src/gs/gather_scatter.f90, src/gs/gs_bcknd.f90
Don't assume nshared or nlocal can be used to test if a gs operation is "shared" or "local". Closes #506
=> Dont assume local .ne. shared during gs operations

.github/workflows/documentation.yml, doc/Doxyfile.in
This adds an external css theme to the Doxygen, taken from https://github.com/ExtremeFLOW/doxygen-awesome-css doc/doxygen-awesome-css 
The theme is cloned to `docs` on the fly in `documentaion.yml`.
=> Add external style to Doxygen

configure.ac, cuda.mk, m4/ax_cuda.m4, src/Makefile.am, src/gs/bcknd/device/cuda/gs_kernels.h
Add the possibility to define `CUDA_ARCH` and `CUDA_CFLAGS` for `nvcc` during configure by issuing
```shell
./configure CUDA_ARCH=... CUDA_CFLAGS=....
```
This will also reenable builds for older devices without `atomicAdd` but without `--enable-device-mpi`
=> Add option to select CUDA flags via configure

configure.ac, hip.mk, m4/ax_hip.m4, src/Makefile.am
Add the possibility to define `HIP_HIPCC_FLAGS` for `HIPCC` during configure by issuing
`./configure HIP_HIPCC_FLAGS=....`
=> Add option to select HIP flags via configure

src/sem/coef.f90, src/sem/dofmap.f90
The dofmap's final procedure was called too early (at least when compiled with CCE) causing the device pointers to `x,y,z` to be freed, thus generating invalid coefficients.
Closes #504
=> Disable the dofmap's final proc.,  fixes coef calc. w. HIP

src/math/bcknd/device/cuda/ax_helm.cu, src/math/bcknd/device/cuda/ax_helm_kernel.h
For lx=8 we have bank conflicts in ax_helm_kernel, which was hurting performance. Padding the shared memory arrays where needed fixes that and improves performance.
=> Padded version of ax_helm_kernel on CUDA to fix Bank Conflicts

configure.ac, m4/ax_cray.m4
Use the Cray provided ROCm module on Cray EX platforms for HIP enabled builds
=> Use Cray provided ROCm on Cray EX platforms

.github/workflows/develop.yml, src/math/bcknd/device/device_math.F90
This adds ROCm/HIP build stages to the develop CI. Note, given the lack of accelerator hardware in the runners, unit tests are not executed.
=> Add ROCm/HIP builds to CI

m4/ax_cuda.m4, m4/ax_hip.m4
Only link against relevant libraries when testing for nvcc/hip.
Relating to (some of) the problems in issue #569
=> Avoid linking against Fortran libraries when testing for nvcc/hipcc

src/math/bcknd/device/hip/ax_helm.hip
Temporary fix, ensuring output generated by #579 is only printed by one rank in neko's logging backend via the c interface #580
=> Route axhelm autotune output to neko's log backend

src/device/cuda_intf.F90, src/device/device.F90, src/device/hip_intf.F90, src/gs/bcknd/device/cuda/gs.cu, src/gs/bcknd/device/gs_device_mpi.F90, src/gs/bcknd/device/hip/gs.hip, src/gs/bcknd/device/hip/gs_kernels.h, src/gs/gather_scatter.f90
**Rework device aware MPI gs alg.**
**Send:**
Either, issue one asynchronous gather-scatter pack kernel per, to be sent, message, instead of packing all buffers at once. or issue a global device sync, sync on each packing stream, followed by issuing the non-blocking send (old way).
**Recv:**
Either, issue one asynchronous gather-scatter unpack kernels per received MPI message in gs, or wait for all messages to arrive. 
The strategy is selected at runtime, and can be different for each `gs_t`, and for each device in a `gs_t`
=> Runtime selection of Sync. / Async. gs pack/unpack w. device MPI

src/math/bcknd/device/cuda/math.cu, src/math/bcknd/device/hip/math.hip, src/math/bcknd/device/opencl/math.c
Changed all malloc and free of bufred in the glsc3 routines to use pinned memory.  Avoiding race condition that could result in host memory being created with MallocHost and freed with free, and making sure we are always using pinned memory for the transfers.
=> updated glsc3 routines to pin the malloc in all glsc3 routines

src/krylov/bcknd/device/cuda/gmres_aux.cu, src/krylov/bcknd/device/hip/gmres_aux.hip
Device reduction buffers aren't resized appropriately if a GMRES solver is used with different `lx` in the same session, e.g. via `pyNeko` or at different multigrid levels.
=> Fix (re)size of gmres reduction buffers

src/math/bcknd/device/opencl/math.c
This PR mainly revert the changes introduced in #602 and #605. To use pinned memory correctly in OpenCL, we need to use `cl_mem` for the "host" buffer and `clEnqueueMapBuffer` to map the memory object.
=> Fix invalid use of pinned memory in OpenCL, causing a runtime crash

src/fluid/fluid_pnpn.f90
Init with a zero dimensional spaces breaks certain backends, e.g. OpenCL
=> Don't init. projection for a zero dimensional space

src/fluid/bcknd/device/cuda/fluid_abbdf.cu, src/fluid/bcknd/device/cuda/makeabf_kernel.h, src/fluid/bcknd/device/cuda/makebdf_kernel.h, src/fluid/bcknd/device/fluid_abbdf_device.F90
Remove redundant arrays in abbdf kernels, reducing memory traffic by ~70% and kernel runtime by ~30%
=> Reduce memory traffic in abbdf CUDA kernels 

examples/hemi/hemi.case
Change from the invalid uniform inflow profile to a blasius one for the hemi example.
Ref: #633
=> Use a blasius profile in the hemi example

src/math/bcknd/device/cuda/math_kernel.h
Reverts ExtremeFLOW/neko#643 this caused a slowdown for certain problem sizes
=> Revert "Transpose glsc3_many kernel, improving memory traffic"

src/fluid/bcknd/device/fluid_abbdf_device.F90, src/fluid/bcknd/device/hip/fluid_abbdf.hip, src/fluid/bcknd/device/hip/makeabf_kernel.h, src/fluid/bcknd/device/hip/makebdf_kernel.h, src/fluid/bcknd/device/opencl/abbdf_kernel.cl, src/fluid/bcknd/device/opencl/fluid_abbdf.c
- Reduce memory trafic in abf and bdf kernels (HIP), based on the CUDA opt from EuroHack22
- Reduce memory trafic in OpenCL kernels
=> Port EuroHack22 optimisations to HIP/OpenCL kernels

src/math/bcknd/device/cuda/math.cu, src/math/bcknd/device/cuda/math_kernel.h
Use a shuffle warp reduction for `glsc3` routines. Reduces runtime with ~15% (and shared memory load by 99%)
**Note requires CUDA > 8**
=> Change CUDA glsc3 to use shuffle warp reduce

bench/tgv32/tgv.f90, examples/lid/lid.f90, examples/lid/lid2d.f90, examples/tgv/tgv.f90, src/common/user_intf.f90, src/simulation.f90
Pass down parameters to `user_check` to allow access to e.g. the Reynolds number, fixes #640
Note: This breaks all existing examples using `user_check`. All provided examples have been updated.
=> Pass down parameters in user_check

src/io/nmsh_file.f90, src/io/re2_file.f90, src/io/rea_file.f90, src/io/vtk_file.f90, src/mesh/hex.f90, src/mesh/mesh.f90, src/mesh/quad.f90, src/sem/dofmap.f90
The assumption is to keep backward compatibility and do not rewrite file format and converters used at pre-proessing step. Only neko internals are changed and the points are swapped at the file reading step. Periodic bc, dof numberring and grid generation are corrected as well.
Stuff left to change/test:
- mesh file writers (e.g. nmsh_file_write) have to swap points
- curved faces/edges are not tested yet
- vtk file writers
- krylov/pc_hsmg.f90 should be checked as it operates on elements
=> Consitent symmetric vertex notation

src/gs/bcknd/device/hip/gs.hip
This fixes the divergence observed on LUMI-G, when an asynchronous gather-scatter strategy was picked.
=> Fix invalid offset in HIP async. GS pack

.github/workflows/develop.yml, .github/workflows/main.yml
Revert the change in pFUnit such that `error stop` is used to mark failed tests.
With the current use of `stop`, automake `make check` can't identify failed tests when using GNU Fortran
=> Patch pFUnit, fixing integration tests

src/krylov/bcknd/device/cuda/gmres_kernel.h, src/krylov/bcknd/device/gmres_device.F90, src/krylov/bcknd/device/hip/gmres_kernel.h
* Use proper `c_sizeof` instead of magic constants
* Don't allocate unnecessary big (unused) host arrays, instead of `allocate(x(n))`, use `allocate(x(1))` and use the scalar array as target in `device_associate`
=> Cleanup and reduce (host) memory usage in device GMRES

src/adt/htable.f90, src/io/re2_file.f90, src/mesh/mesh.f90
Reduces memory footprint for generating meshes from re2 files. Now you roughly need 4-5GB of free RAM for each 1M elements in the mesh.
=> Rea2nbin fixes

bench/tgv32/tgv.f90, examples/cyl_boundary_layer/cyl_bl.f90, examples/lid/lid.f90, examples/rayleigh-benard/rayleigh.f90, examples/tgv/tgv.f90, examples/turbpipe/pipe.f90, reframe/src/tgv.f90, src/case.f90, src/common/user_intf.f90, src/simulation.f90
Make naming consistent in exposed user interface, expanding abbreviations e.g. change usr -> user. fixes #632
**Note:** This is a breaking change, and affect most provided examples
=> Consistent spelling in exposed intf, usr -> user

src/gs/gs_mpi.f90, src/io/chkp_file.f90
This fixes the internal compiler error `copy_simple failed (unknown node type 442)` thrown by NAG
=> Fix ICE with NAG

doc/pages/case-file.md, src/comm/mpi_types.f90, src/common/parameters.f90
Add an array of sixteen user-defined parameter `user(:)`, fix #636
=> Add user-defined parameters

.github/workflows/develop.yml, .github/workflows/main.yml, patches/nvhpc_bge.patch
This adds the NVIDIA Fortran to the integration tests.
With the latest release of NVHPC toolkit v22.11, the NVIDIA Fortran compiler is now able to compile the REAL64 version of Neko with a minimal set off patches (`patches/nvhpc_bge.patch`) to disable missing F2008 features.
=> Add NVIDIA Fortran to the integration tests

src/case.f90, src/common/checkpoint.f90, src/io/chkp_file.f90, src/simulation.f90
Adds a scalar as an optional field in a checkpoint. Maybe we should consider moving chkp up from fluid into case. In some sense we save a case rather than only the fluid fields. 
There is still a risk that one sets incorrect ics for scalars as we do not ensure that there are no jumps between elements, but before addressing that we maybe should consider how we would like to handle user defined ics and bcs for multiple fields.
=> Scalar checkpoint

src/math/bcknd/device/cuda/cfl_kernel.h, src/math/bcknd/device/cuda/opr_cfl.cu, src/math/bcknd/device/hip/cfl_kernel.h, src/math/bcknd/device/hip/opr_cfl.hip
This avoids copying large arrays for over to the host for a final reduction (`fmax`)
=> Use warp shuffle in CFL calculation to reduce data transfer

src/.depends, src/.depends_device, src/Makefile.am, src/common/bcknd/device/cuda/projection.cu, src/common/bcknd/device/cuda/projection_kernel.h, src/common/bcknd/device/device_projection.F90, src/common/bcknd/device/hip/projection.hip, src/common/bcknd/device/hip/projection_kernel.h, src/common/projection.f90, src/math/bcknd/device/cuda/math.cu, src/math/bcknd/device/device_math.F90, src/math/bcknd/device/device_mpi_reduce.h, src/math/bcknd/device/hip/math.hip
- Remove redundant HtoD copies in project on (iff device MPI is present) (CUDA)
- Fix missing template argument
- Add HIP backend
- Disable for unfinished OpenCL part
- Avoid redudant DtoH copies
- Remove redundant HtoD transfers in project ortho (CUDA)
- Fix missing template arguments
- Remove redundant HtoD transfers in project ortho (HIP)
=> Fuse kernels and remove redudant HtoD (DtoH) transfers in proj.

src/math/bcknd/device/opencl/tensor.c, src/math/tensor.f90
This fixes a bug in the tensor interface, preventing the OpenCL backend to be called. 
Also, this pr fixes the hsmg precon for the OpenCL backend (related to #373)
=> Fix tnsr3d w. OpenCL bcknd

src/math/bcknd/device/opencl/schwarz.c, src/math/bcknd/device/opencl/schwarz_kernel.cl
Backport shared memory optimisations for CUDA/HIP #727 top OpenCL schwarz  (part of #373)
=> Backport shmem opt and fix various bugs in OpenCL schwarz precon.

src/io/nmsh_file.f90
A simple check in the nmesh reader to make life easier in certain cases.
=> Die if there is an error opening the mesh file

src/common/projection.f90
This is a temporary solution to enable the OpenCL backend in projections (refs #373). 
To be removed once the `_many` kernels has been reworked to support OpenCL
=> Fix projections for OpenCL backend

src/krylov/bcknd/device/gmres_device.F90, src/krylov/krylov_fctry.f90
This add similar workarounds as in projections for OpenCL (to be removed once the `many` kernels are better supported). Furthermore, this also brings enough OpenCL functionality into Neko to efficiently run a full flow case (fixes #373)
=> Add support for OpenCL in GMRES solver

m4/ax_cuda.m4
This problems occurs if Neko is built with ADIOS2 (under certain conditions), fixes #717
=> Don't pass all C++ related LDFLAGS to nvcc

src/gs/bcknd/device/gs_device_mpi.F90
This is a temporary fix, of a possible race condition when using a GS strategy of 3 or more. The fix will be removed once we can merge in the new device and gather-scatter work from the ENCCS hackathon.
=> Fix race condition in gather-scatter (strtgy > 2)

src/case.f90, src/common/ext_bdf_scheme.f90, src/fluid/bcknd/device/device_fluid_plan4.f90, src/fluid/fluid_plan4.f90, src/fluid/fluid_pnpn.f90, src/fluid/fluid_volflow.f90, src/scalar/scalar_pnpn.f90, src/simulation.f90
This is the beginning of the effort towards issue #114 and the cleanup of the BDF class.
* I introduce  a `time_scheme_t` as an ABC for both BDF and EXT, which also get their own type. This is done mainly to make it possible to test schemes individually, but I think there is a certain elegance in having them both sharing a common interface.
* I have, however, kept everything in the same module for now, since the change of us adding more schemes seems minimal.
* To minimally change the rest of Neko, `ext_bdf_scheme_t` remains, but is now just a composition of a `bdf_time_scheme_t` and `ext_time_scheme_t`. 
* `set_time_order` is changed to `init` because it not only set the order, but also took care of the device pointer, so it is typical a constructor.
* As a side-bonus, `nab` is gone, …
=> Refactor ext_bdf_scheme_t

.gitignore
Cherry-picked out of #809, so this can be merged and just better PR granularity.
=> Add output fields from examples to .gitignore

configure.ac, src/math/fast3d.f90, tests/.gitignore, tests/Makefile.am, tests/fast3d/Makefile.in, tests/fast3d/test_fd_weights_full.pf
* Improves the documentation a lot. The previous one is simply wrong, this routine does not evaluate anything, just computes weights! All the info is taken from Fornberg's book, which seems very nice, by the way.
* Added 2 simple tests that serve as documentation as well. Weights for simple linear interpolation and a classical 2nd order central difference.
* Refactored `xx` to `xi`. Sorry, couldn't resist. `xi` corresponds nicely to the $\xi$ in the mathematical formulation.
=> Improvements and tests for fd_weights_full 

src/field/scratch_registry.f90, tests/scratch_registry/test_scratch_registry.pf
This cherry-picks commits pertaining to the scratch registry from #809, so that #809 does not become a monster PR.
- Adds possibility to relinquish several fields at once by passing an array of indices.
- Adds a test for the above.
- Fixes a bug in the destructor, now checks if stuff has been allocated before attempting to free it.
=> Scratch registry improvements

src/common/ext_bdf_scheme.f90
Initializes the counter in the `time_scheme_t` class to 0. Missed in the refactoring and now discovered during testing. Since this totally breaks the code unless it magically inits to 0, we gotta merge this asap, so separate PR.
=> Hotfix time_scheme%n initialization

.github/workflows/develop.yml, configure.ac, src/common/bcknd/cpu/rhs_maker_cpu.f90, src/common/bcknd/device/rhs_maker_device.F90, src/common/bcknd/sx/rhs_maker_sx.f90, src/common/ext_bdf_scheme.f90, src/common/rhs_maker.f90, src/fluid/bcknd/device/fluid_abbdf_device.F90, tests/.gitignore, tests/Makefile.am, tests/ext_bdf_scheme/Makefile.in, tests/ext_bdf_scheme/test_bdf.pf
- The computation of the coeffs for the BDF scheme no longer uses a messy linear solver. Instead, they are computed using explicit formulas, taken from a [technical note by Nishikawa](https://www.researchgate.net/publication/351082535_Derivation_of_BDF2BDF3_for_Variable_Step_Size). 
- The above fixes the maximum order to 3, which anyway is the maximum used. 
- However, we can easily extend to higher order later if we want, because the subroutine `fd_weights_full` that we have can be used to compute the coefficients for arbitrary order. I am surprised Nek5000 did not use that, actually! It requires a bit of array reordering, etc, so for now I went for the explicit formulas.
- Quite detailed documentation for the BDF scheme is provided. There are two somewhat surprising conventions one …
=> Cleanup of bdf_time_scheme_t; adding its docs and tests

src/device/cuda_intf.F90
Priority range is 0 and -5 for lowest and highest priority, respectively on recent devices including A100 (and Turing CC 7.5).
=> Correct CUDA stream priorities of glb_cmd_queue/aux_cmd_queue

.github/workflows/develop.yml
Temporarly disable nvhpc builds in CI until the ICE is fixed.
=> Disable nvhpc builds for develop CI

src/gs/bcknd/device/gs_device.F90
Fix "not implemented" error due to missing "device_event" interface for OpenCL
=> Fixed regression in OpenCL gs

configure.ac, m4/ax_cray.m4
Don't check loaded modules on a Cray EX unless CrayPE wrappers are used, fixes #855
Note if CrayPE wrappers aren't used, full search paths has to be given to e.g. `--with-hip`, `--with-blas` etc
=> Check if CrayPE wrappers are used on Cray EX systems

examples/rayleigh-benard/rayleigh.case, examples/rayleigh-benard/rayleigh.f90, src/bc/bcknd/device/cuda/inhom_dirichlet.cu, src/bc/bcknd/device/cuda/inhom_dirichlet_kernel.h, src/bc/bcknd/device/device_inhom_dirichlet.F90, src/bc/bcknd/device/hip/inhom_dirichlet.hip, src/bc/bcknd/device/hip/inhom_dirichlet_kernel.h, src/bc/bcknd/device/opencl/inhom_dirichlet.c, src/bc/bcknd/device/opencl/inhom_dirichlet_kernel.cl, src/bc/usr_inflow.f90, src/case.f90, src/common/user_intf.f90, src/scalar/scalar_pnpn.f90, src/scalar/scalar_scheme.f90
Enables user boundary conditions for the scalar. We should look over the structure of the BCs as we have discussed, but that would be rather intrusive.
User bcs for the scalar is enabled by default for all zones that are not labeled, meaning that one gets a warning if one runs with scalar enabled on a mesh with hardcoded bcs in the mesh without setting the scalar user bc.
I will add an example RBC case in another PR to show the usage.
I have not tested on HIP and OpenCL.
=> Scalar user bc

src/bc/bc.f90, src/bc/blasius.f90, src/bc/non_normal.f90, src/bc/symmetry.f90, src/bc/usr_inflow.f90
- Make sure to nullify pointers
- Remove troublesome final calls, causing issues for device builds w. gcc 13.1
=> Fix finalisation in bc

doc/pages/index.md
Put all manual pages as subpages under the main Neko Manual page
=> Structure manual

src/case.f90, src/common/bcknd/cpu/rhs_maker_cpu.f90, src/common/bcknd/device/rhs_maker_device.F90, src/common/bcknd/sx/rhs_maker_sx.f90, src/common/rhs_maker.f90, src/fluid/bcknd/cpu/pnpn_res_cpu.f90, src/fluid/bcknd/device/pnpn_res_device.F90, src/fluid/bcknd/sx/pnpn_res_sx.f90, src/fluid/fluid_pnpn.f90, src/fluid/fluid_scheme.f90, src/fluid/fluid_volflow.f90, src/fluid/pnpn_res.f90, src/neko.f90
Towards removing temporaries in fluid_pnpn.  WIP, but things seem to work. I don't like that one does a linear search through the scratch registry 8 times per time-step. But this should not be overthought, since the direction is to change the interfaces of the stuff called inside `step` in a way that I can just pass the registry to them.
=> Better temporaries handling in fluid

src/Makefile.am, src/common/bcknd/device/cuda/projection.cu, src/common/bcknd/device/hip/projection.hip, src/krylov/bcknd/device/cuda/gmres_aux.cu, src/krylov/bcknd/device/hip/gmres_aux.hip, src/math/bcknd/device/cuda/math.cu, src/math/bcknd/device/cuda/opr_cfl.cu, src/math/bcknd/device/device_mpi_op.h, src/math/bcknd/device/device_mpi_reduce.c, src/math/bcknd/device/device_mpi_reduce.h, src/math/bcknd/device/hip/math.hip, src/math/bcknd/device/hip/opr_cfl.hip
Add a dummy wrapper for `MPI_OP` for the `device_mpi_allreduce` wrapper.
This fixes #903.
=> Allow for different MPI_OP in device_mpi_allreduce wrappers

src/adt/htable.f90, src/adt/uset.f90, src/field/scratch_registry.f90, src/fluid/fluid_volflow.f90
Add final procedures, nullify and target specifiers to avoid danling pointers
To check, compile with NAG and -C=dangling, and run with NAGFORTRAN_RUNTIME_OPTIONS=show_dangling
=> Fix dangling pointers

src/fluid/advection.f90, src/fluid/fluid_pnpn.f90, src/scalar/scalar_pnpn.f90
Renames `apply` to `compute` in advection classes, as discussed in #822. Also adds a bit of comments/docs.
=> adv%apply -> adv%compute + docs

examples/cyl_boundary_layer/cyl_bl.f90, examples/lid/lid.f90, examples/lid/lid2d.f90, examples/rayleigh-benard-cylinder/rayleigh.f90, examples/rayleigh-benard/rayleigh.f90, reframe/src/rayleigh.f90, src/bc/bc.f90, src/bc/blasius.f90, src/bc/dirichlet.f90, src/bc/dong_outflow.f90, src/bc/facet_normal.f90, src/bc/inflow.f90, src/bc/symmetry.f90, src/bc/usr_inflow.f90, src/bc/usr_scalar.f90, src/bc/wall.f90, src/common/user_intf.f90, src/fluid/fluid_pnpn.f90, src/fluid/fluid_scheme.f90
This extends the bc definition to allow for (optional) passing down current simulation time and/or time-step, fixes #902.
**Note** this breaks most user provided bcs
=> Add methods to pass down simulation time and/or time-step to bcs

configure.ac, src/.depends, src/Makefile.am, src/common/sampler.f90, src/common/time_based_controller.f90, tests/.gitignore, tests/Makefile.am, tests/time_based_controller/Makefile.in, tests/time_based_controller/test_time_based_controller.pf
* The `sampler` class implemented the logic for determining whether we need to write or not.
* I put this in a separate class, called `time_based_controller`.
* The reason is that we may want to use this in other contexts. Basically for anything, which should not be executed at each time-step, but rather based on user input. One immediate application is execution of `simcomps`.
* This makes the `sampler` class less heavy as bonus.
Not sure to be honest if the sampler works correctly atm, I just want to commit WIP, therefore, the don't merge label. But it *seems* to work :-), and the code is clean enough to review.
=> Put check on whether to execute an action based on time value in a separate class

src/device/cuda_intf.F90
fixes possible invalid device context with OpenMP and UCX
=> Ensure each thread is assigned to the same device

examples/tgv/tgv.case, src/simulation_components/simulation_component.f90, src/simulation_components/vorticity.f90
* Adds 2 `time_based_controller`s to the base simcomp type, one for compute, and one for output.
* For compute, default to every time step.
* For output, default to the same as the settings for compute.
* The actual implementation of the computation is now in the deferred `compute_` procedure, which is wrapped in the `compute` procedure in the base class, which serves as the public interface. The wrapper executes `compute_` based on the controller.
* No logic for output implemented for now, so the controller is just hanging there, but will surely be needed in a future update.
=> Add controllers to simcomps

doc/pages/case-file.md, reframe/src/rayleigh.case.template, src/case.f90, src/common/time_based_controller.f90
* Adds `never` as an option for the `time_based_controller`.  Useful for benchmarking or having a simcomp do no output, for example.
* Forces `nsamples` to be positive.
=> Adds output control "never" and throw for non-positive nsamples

examples/rayleigh-benard-cylinder-probes/rayleigh.f90, src/.depends, src/common/probes.F90, src/sem/point_interpolator.f90, tests/point_interpolation/point_interpolation_parallel.pf
Got rid of `findpts_eval` for the interpolation in `probes%interpolate`. Also removed `coef_t` from point_interpolator as it is not using it, and adjusted the RBC example.
=> Probes with point interpolator

src/device/device.F90, tests/device/device.pf, tests/device_math/device_math_parallel.pf
Ensure that synchronised device memcpy calls are syncing on the calling stream and not the (unused) NULL stream. 
If `sync=.true.` and no stream is given for `device_memcpy`, it will default to synchronise on the (Neko default) `glb_cmd_queue` stream.
This hopefully solves the sync. issues observed in #972
=> Ensure memcopies sync on the correct stream

src/io/data_streamer.F90
The cray compiler in lumi complained about the intent of one of the variables. I have modified it such that it does not. 
The variable is not really touched. In the future I will perhaps change the intent to be safer.
=> modified the intent of coef in _init

src/Makefile.am, src/comm/comm.F90.in, src/comm/comm.h, src/comm/comm_wrapper.c, src/comm/parmetis_wrapper.c, src/gs/bcknd/device/device_mpi.c, src/math/bcknd/device/device_mpi_reduce.c, src/math/bcknd/device/device_mpi_reduce.h
Since we can no longer assume `NEKO_COMM` is the same as `MPI_COMM_WORLD`, the Fortran communicator is wrapped into a proper C `MPI_Comm` type, and the C/C++ backends has been changed to use `NEKO_COMM` instead of `MPI_COMM_WORLD`
=> Fix wrapping and expose of Fortran MPI communicator to C/C++ bcknds

src/io/re2_file.f90
Fixed SEGV if the parsed label id `label` is greather than `NEKO_MSH_MAX_ZLBLS` (or smaller than one)
=> Throw an error if the re2 file label id is out of range

src/fluid/bcknd/cpu/pnpn_res_cpu.f90, src/fluid/bcknd/device/pnpn_res_device.F90, src/fluid/bcknd/sx/pnpn_res_sx.f90, src/fluid/fluid_volflow.f90, src/krylov/bcknd/cpu/bicgstab.f90, src/krylov/bcknd/cpu/cacg.f90, src/krylov/bcknd/cpu/cg.f90, src/krylov/bcknd/cpu/gmres.f90, src/krylov/bcknd/cpu/pipecg.f90, src/krylov/bcknd/device/cg_device.f90, src/krylov/bcknd/device/gmres_device.F90, src/krylov/bcknd/device/pipecg_device.F90, src/krylov/bcknd/sx/cg_sx.f90, src/krylov/bcknd/sx/gmres_sx.f90, src/krylov/bcknd/sx/pipecg_sx.f90, src/krylov/krylov.f90, src/krylov/krylov_fctry.f90, src/krylov/precon.f90, src/math/ax.f90, src/math/ax_helm_fctry.f90, src/math/bcknd/cpu/ax_helm.f90, src/math/bcknd/device/ax_helm_device.F90, src/math/bcknd/sx/ax_helm_sx.f90, src/math/bcknd/xsmm/ax_helm_xsmm.F90
This mostly fixed use statements in Krylov solver types, making the use `only`. Also adds `private` at module scope in some places. A little bit of docstrings. No functionality is changed.
=> Fix privacy and imports in krylov solvers

src/.depends, src/mesh/point_zone.f90, src/mesh/point_zone_factory.f90, src/mesh/point_zones/box_point_zone.f90, src/mesh/point_zones/sphere_point_zone.f90
I think it makes more sense like this, so that `map` and `finalize` are called separately and **only** in point zone factory. That way it will also be easier to change the workflow if necessary.
=> Move finalize and map in point zone factory

.github/workflows/develop.yml
Fix issues with recent oneapi setup scripts, and enable `fix` as a compiler backend
=> Fix CI for Intel compilers

src/sem/speclib.f90
Fix the following warning:
Warning: sem/speclib.f90, line 495: Low-precision data-value assigned to high-precision data-object
=> Fix invalid precision in speclib

src/bc/blasius.f90, src/bc/dong_outflow.f90, src/bc/usr_inflow.f90, src/bc/usr_scalar.f90, src/common/checkpoint.f90, src/fluid/fluid_pnpn.f90, src/scalar/scalar_pnpn.f90
Further fixes of the restarts... Also found a data race for using the device for user bcs due to the asynchronous memcpy.
I anticipate that both Adalberto and Siavash should observe more similar results now. 
We should perhaps go further with regards to async memcpy and try to limit async to things that happen in the iterative solvers to avoid things like this.
=> Restart fixes - second round

src/io/csv_file.f90
Fixes #1079 
See https://github.com/ExtremeFLOW/neko/issues/1079#issuecomment-1864994418 for the full explanation.
In summary, it seems that declaring pointers as:
```.f90
type(vector_t), pointer :: vec => null()
type(matrix_t), pointer :: mat => null()
```
Does not properly set the pointers to `null()`. I have found a workaround, to manually set `vec` and `mat` to `null`:
```.f90
type(vector_t), pointer :: vec
type(matrix_t), pointer :: mat
nullify(vec)
nullify(mat)
```
=> Manually set vec and mat to null in `csv_file_write`

src/common/bcknd/cpu/rhs_maker_cpu.f90, src/common/bcknd/device/rhs_maker_device.F90, src/common/bcknd/sx/rhs_maker_sx.f90, src/common/rhs_maker.f90, src/scalar/bcknd/cpu/scalar_residual_cpu.f90, src/scalar/scalar_pnpn.f90, src/scalar/scalar_residual.f90, src/scalar/scalar_scheme.f90
* Follows what is already done for fluid, and seems to have raised no complaints. For scalars, the residuals subroutines don't use temporaries, only the rhs makers do. Note that on the device, no temporaries are used at all, so there this simply deletes unnecessary arguments. 
* The scalar scheme types now `use ...., only`. 
Also, some improvements to docstrings here and there.
=> Use the global scratch manager for scalar rhs

src/simulation_components/simulation_component_factory.f90
When an unknown simulation component is specified we should throw an error and stop rather than segfaulting.
=> Fix a segmentation fault.

m4/ax_cray.m4
This fixes an issue with detecting ROCm on CRAY EX platforms when using the wrappers (CC,ftn) but a none HPE provided rocm module
=> Fix ROCm detection on Cray EX platforms for none HPE provided modules

src/krylov/bcknd/device/pipecg_device.F90, src/math/bcknd/device/cuda/math.cu, src/math/bcknd/device/cuda/math_kernel.h, src/math/bcknd/device/device_math.F90, src/math/bcknd/device/hip/math.hip
Fixed too high starting residual due to double reduction (glsc3 + MPI_Ireduce). The patch introduces vlsc3 for devices.
=> Fix invalid starting residual for (device) pipecg

src/.depends, src/Makefile.am, src/case.f90, src/common/time_based_controller.f90, src/io/chkp_output.f90, src/io/file.f90, src/io/fld_file.f90, src/io/fld_file_output.f90, src/io/fld_output.f90, src/io/fluid_output.f90, src/io/fluid_stats_output.f90, src/io/mean_flow_output.f90, src/io/mean_sqr_flow_output.f90, src/io/output.f90, src/simulation_components/simulation_component.f90, src/simulation_components/vorticity.f90
This PR introduces:
- `output_control: "global"` for simcomps, which syncs `output_control` and `output_value` with the fluid. Useful to control output of multiple thing by a single set of parameters.
- `fld_output_t`, which is much luck `fluid_output` but does not add the fluid fields to the output. Can be used to output any number of arrays to a new fld.
- Working on outputing simcomp fields to files. What I have now is that if you don't specify `output_filename`, the field (e.g. vorticity) gets added to the `fluid_output` in the case. Otherwise, a new fld file is created. Opinions welcome.
- A small refactor to the `output_t` constructor, so that one can use `init` in descendents as is now standard.
When working on this I realized that e.g. the probes simcom just manages its own …
=> Generic fld_output, global output_control and simcomp file output

src/io/fld_file_output.f90
`fld_file_output` always allocates 3 fields in the field list instead of using the `nfields` argument. This fixes this bug. Please merge as soon as possible :-).
=> Fix field allocation in fld_field_output

src/common/json_utils.f90
Useful for parsing stuff like arrays of source terms, simcomps, etc in the JSON. Not used atm, but soon :-).
=> Add helper to extract json array items as json objects

doc/pages/case-file.md, src/fluid/fluid_source_term.f90, src/fluid/fluid_user_source_term.f90, src/scalar/scalar_source_term.f90, src/scalar/scalar_user_source_term.f90, src/source_terms/const_source_term.f90, src/source_terms/source_term.f90
* Adds `start_time` and `end_time` json parameters for source terms, so as to limit the execution of the source term in time whe necessary.
* Does not affect the user source terms, because they don't get init from the json and things become difficult. Warnings are issued to the log if the keywords are present. The idea is that you can anyway always put any `ifs` you need right in your user source code.
* To accommodate this, the interface of the `source_term_t` is changed to have the new parameters (descendents have to parse the start_time and end_time from the json now before sending them to the base type constructor). The deferred routine is now called `compute_`, whereas `compute` wraps that with the check on the current time and the user-selected time start and end time. This is …
=> Add start and end time for source addition, update documentation

src/math/operators.f90
* Adds `only` to imports in operators.f90
* Adds docstrings to the operators. I am unsure about one parameter in the `ortho`, please help :-).
* Renamed `c_Xh` to `coef` in `curl`, because all the other operators use `coef`.
=> Docstrings, and "only" for operators

src/io/fld_file.f90
Removed the check_exist statements, and added an error statement in case `MPI_File_open` does not find the `.f00*` files. The existence of the `.nek5000` meta file is checked right before so all cases should (?) be covered.
=> Fix fld reader

doc/pages/case-file.md, doc/pages/point-zones.md, src/.depends, src/Makefile.am, src/mesh/point_zone_factory.f90, src/mesh/point_zones/cylinder_point_zone.f90
The cylinder point zone is constructed from its end points and radius. This allow the user to define the cylinder in arbitrary orientations and sizes.
=> Addition of new point zone type: Cylinder.

src/common/json_utils.f90
Useful to not get garbage in the read array. For example, for bc_labels, we can default to "not" as we do now outside of JSON, or some similar dummy value.
=> Add possibility to provide default string for json string array reader

src/scalar/scalar_scheme.f90
There is an issue with how we parse bc_labels, which seems to so far simply gone undetected. By default, the size of the bc_labels array is `NEKO_MSH_MAX_ZLBLS`. However, when we pass bc_labels to the `json_get`, the array gets reallocated to the size as found in the case file. So, all the loops that parse bc_labels and iterate up to `NEKO_MSH_MAX_ZLBLS` are going through garbage.  Now, most of these loops search for an exact string comparison, which will essentially never happen.
But for the scalar, we search for the *first element*  of the label to be "d" (or "n", once Neumann is merged), and *that* can actually randomly be there for a garbage bc_label item, which will of course crash everything. Therefore, I fix the bc_labels to be an assumed shape array and iterate up to its size. …
=> Fix bc_label loop in scalar_scheme_t

makeneko.in
Change  the `makeneko` compile line from `$1` to `$@` to allow for several files to be compiled at once.
=> Extend makeneko for several arguments

examples/scalar_mms/README.md, src/mesh/mesh.f90, tests/field/field_parallel.pf, tests/mean_field/mean_field_parallel.pf, tests/mean_sqr_field/mean_sqr_field_parallel.pf, tests/scratch_registry/test_scratch_registry.pf
Seems like there was an issue that the facets belonging to a periodic facet could be changed by a neighboring element, but then not added to the table correctly when generating connectivity. 
This PR changes this. For future developments, we should note though that if the entire side is not periodic but a mesh would change from periodic to some other BC along a boundary, this is not necessarily well defined if the element it changes on is not guaranteed to be on the same rank.
=> Fix periodic

src/les/bcknd/cpu/vreman_cpu.f90, src/les/vreman.f90, src/simulation_components/les_simcomp.f90
* Fixes a bug in how nut is computed, indexing was incorrect.
* deallocates les_model in the les_simcomp in the destructor.
* Calls "free" in the beginning of constructors in vreman and les simcomp as per convention.
=> Fix Vreman model nut computation and improve destructors

src/math/operators.f90
Fix the invalid CFL calculation for CPU builds with CCE v15.0.1
=> Fix invalid CFL calculation using CCE

examples/TS_channel/README.md
Lower resolution is okay for transitional case, which requires far less computational cost
=> Update README.md of TS wave test examples

.gitignore
We now ignore all files with no extension. Except an explicit list.
Additionally added some temporary file types to the ignored list.
=> Updates to the gitignore

src/mesh/point_zones/cylinder_point_zone.f90
This pull request fixes a mistake in the cylindrical point zone calculation. The calculation of the projection point was incorrect, resulting in incorrect distance calculations. This PR updates the calculation to use the correct centerline vector and projection point.
=> Fix mistake in cylindrical point zone

contrib/average_field_in_space/average_field_in_space.f90, examples/turb_channel/README.md, src/neko.f90, src/sem/map_1d.f90
Adds support for computing average in 2 spatial directions directly if there is more than one homogenous direction (for example channel flow).
We also update map_1d so it does not break if compiled with GPU backend, it now gives a warning instead. Still, the mapping is only available on the CPU currently.
=> Average fields in two directions

tests/point_interpolation/point_interpolation_parallel.pf
Fixes #1155
- Added setup and tear down
- Renamed subroutines to avoid truncation error from Fortran compilers.
=> Point interpolation test

src/field/field.f90
For convenience and to be wrapped in field_list_t. 
field%dof%size() is actually called in a lot of places in the code, so it is nice to have a wrapper directly in field_t.
=> Add a wrapper for dofmap%size in the field_t type

contrib/average_field_in_space/average_field_in_space.f90
minor changes on contrib/average_field_in_space: the original one does not allow spatial-avg of multiple time steps, now it's fixed.
=> fix bugs in average_field_in_space: allow avg on multiple time steps

CITATION.cff
Include all authors with at least one commit in `develop` to the citation file. ref: #1104 and #1188
=> Updated cff file to include all authors

src/math/bcknd/device/cuda/ax_helm.cu
Add the missing call to padded version of Ax for lx8 (removed by accident during a refactoring). Furthermore, based on profiling, use padded version for lx4 and lx16.
Performance increase: 4% (lx4), 18% (lx8) and 52% (lx16)
=> Add missing call to padded version of Axhelm

src/bc/field_dirichlet_vector.f90
Added if statements in the `field_dirichlet_vector:apply_vector(_dev)` to avoid runtime errors when called without `t` or `tstep`
=> modify apply_vector to account for optional args

src/math/operators.f90, src/qoi/drag_torque.f90
This changes the strain_rate operator to actually return the strain rate instead of its double (which I think I copied from Nek5000). The x2 convention is easy to forget about and now caused some issues with the implemention of models for the stress formulation branch.
On develop, the operator is not used.
=> Change strain rate to include the 1/2 factor

configure.ac, doc/pages/user-guide/case-file.md, doc/pages/user-guide/installation.md, m4/ax_cray.m4, m4/ax_hdf5.m4, src/.depends, src/Makefile.am, src/case.f90, src/field/field_series.f90, src/io/chkp_output.f90, src/io/file.f90, src/io/hdf5_file.F90, src/simulation.f90
This add support for reading/writing (parallel) HDF5 files. The new format has been enabled as an optional format for checkpoints, but the backend can read/write most of our output lists.
=> HDF5 Support

README.md
To make life easier, removed some more advanced options from the readme and added how to compile json-fortran. 
Easier than looking into https://github.com/ExtremeFLOW/neko/blob/develop/.github/workflows/develop.yml for how to compile as I am doing now.
Not perfect, but I think this would be a significant improvement, in particular it's rather easy to copy-paste and get something up and running.
=> README with JSON-Fortran

src/bc/bc.f90
This is a hotfix to prevent some of the observed memory issues observed in mark zones from list, most likely caused by `split_string`
The intent is to remove this as soon as the bcs are overhauled
=> Reduce the risk of memory issues in mark zones from list

doc/pages/user-guide/case-file.md, src/bc/field_dirichlet.f90, src/bc/field_dirichlet_vector.f90, src/field/field_list.f90, src/fluid/fluid_pnpn.f90, src/fluid/fluid_scheme.f90, src/neko.f90, src/scalar/scalar_pnpn.f90, src/scalar/scalar_scheme.f90
My main goal here is to reduce the number of additional components in the scheme types necessary to add the user field_dirichlet bcs. Currently we need the bc itself, a field list for the dummy fields in the bc,  a bc_list to store the field_dirichlet bcs themselves, and an update procedure pointer to the user routine.
To trim this down, I put most of these things inside the field_dirichlet types themselves. The only extra thing still in the scalar_scheme is the bc_list. I did not quite dare to add a bc_list to a type to store.. a pointer to itself. However, for the field_dirichlet_vector I could store the bc_list, it just contains the 3 field_dirichlet_bcs that are stored as components inside field_dirichlet_vector.
For the fluid, I use the lists in velocity field_dirichlet to also store …
=> Slight update to field_dirichlet bcs

flinter_rc.yml
- Allow single character after separators (array index).
- Fixed typos.
=> Update of flinter

src/common/bcknd/cpu/rhs_maker_cpu.f90, src/fluid/bcknd/cpu/pnpn_res_cpu.f90
Use standard do concurrent instead of compiler directives to promote vectorisation of loops containing pointers to scratch arrays.
For example using Fujitsu, we see the following
```Fortran
67                         call neko_scratch_registry%request_field(temp1, temp_indices(1))
68                         call neko_scratch_registry%request_field(temp2, temp_indices(2))
69                         call neko_scratch_registry%request_field(temp3, temp_indices(3))
70
<<< Loop-information Start >>>
<<<  [OPTIMIZATION]
<<<    PREFETCH(HARD) Expected by compiler :
<<<      (unknown)
<<< Loop-information  End >>>
71     1                   do i = 1, n
72     1                      temp1%x(i,1,1,1) = ext_coeffs(2) * fx_lag%x(i,1,1,1) + &
73     1 …
```
=> Use standard language constructs to guide vectorisation

.github/workflows/develop.yml, .github/workflows/lint.yml, .github/workflows/main.yml
This pull request includes the following changes:
- Rework of the CI for linting, including separating linting into its own file, performing checks for the repository and all changed files individually, and adding the ability to set a minimum score when calling the action.
- Using the new linting in the main CI workflow.
- Clean up of the workflow.
These changes improve the linting process and make it more clear what can be done to improve it.
As an additional bonus, we now cancel old workflows for a PR when a new commit is submitted. which should help reduce resource usage and speedup return for the valid runs.
=> "Rework CI for linting and use new linting in main CI"

.github/workflows/check_intel.yml
Currntly we rely on manually updating the path to intel compilers when a new version comes out.
This PR solves that by automatically finding the compiler and adding its location to the path.
=> Automatic detection of intel compiler version

makeneko.in, reframe/checks.py, src/common/user_intf.f90, src/neko.f90
Instead of changing the name of the executable, we can print a message to the log if we are running any user extended functions.
Please note, this PR is to the original PR not to the develop branch as I would not start overriding the work of Måns directly.
=> Alternative suggestion to the makeneko naming

.github/workflows/check_depend.yml, .github/workflows/check_gnu.yml, .github/workflows/check_intel.yml, .github/workflows/check_nvidia.yml, .github/workflows/check_reframe.yml
Update the CI to determine the full OS version currently used. This improves caching of dependencies, as an update to the minor version of the runner os might require a recompilation which was not caught previously.
=> OS Version updates

flinter_rc.yml, src/bc/usr_inflow.f90, src/fluid/fluid_scheme.f90
Put the call to `bc_inflow%set_coef` back in fluid scheme that was causing `usr_inflow::usr_inflow_validate` to fail when running with a `"user"` inflow condition since the `usr_inflow_t%c` pointer was never being associated.
=> Fix missing set_coef call for user inflow condition

examples/TS_channel/TS_channel.case
Two point to update with the TS wave test examples:
1. Update the outdated case file to keep accordance with the current time step controller setting. (committed already)
2. Change to a 16^3 elements mesh for a matching result with Schlatter 2005. (under discussion now)
=> Debug: Update TS wave test

src/io/csv_file.f90
The logic here was wrong, there should be a header if the number of actual lines in the file is greater than the number of rows of the array passed for reading.
=> Fix logic in csv_reader to correctly read headers

src/device/hip_intf.F90
Dont know exactly what goes wrong, but something is iffy with hipGetDeviceCount. Do you have any idea what can be the issue @timfelle ?
To be clear, if one does not comment these lines Neko segfaults directly on LUMI.
=> Temp fix to be able to run on LUMI

src/les/dynamic_smagorinsky.f90
Move the setup of the test filter in the init rather in compute which is executed every time step.
Thought it won't take much time, but still better to do it.
=> Quick fix in dynamic Smagorinsky model

doc/pages/developer-guide/dev_patterns.md, flinter_rc.yml
According to our guidelines we must use `only` when using modules.
https://neko.cfd/docs/develop/d0/d47/dev_patterns.html#autotoc_md16
This PR will enforce this.
Closes: #1418
=> Add enforcement of `only` specifications.

contrib/genmeshbox/genmeshbox.f90
Added a log that shows which parameters were used with genmeshbox, to have a trace.
=> Output the commands used with genmeshbox in a separate log file

flinter_rc.yml
Fixes #1428
Solution:
check only lines starting with `use`
=> Fix false restriction on the word "use"

flinter_rc.yml
fixes The rule for spaces between builtin commands and paranthesis also trigger on variables with names ending in the builtin name. (example `phis`, triggers because of `is` ExtremeFLOW/neko#1421
=> Fix the linter issue by only checking full words matching `structs`

src/.depends, src/io/nmsh_file.f90
Adds time for generating mesh connectivity in the log. 
Helps when one has a big case and it takes a long time and one does not know if the simulation has frozen.
If we think this is a good idea perhaps we should add something for gs as well as that also sometimes takes some time. I was thinking one could perhaps generate the buffers from a previous gs_t to drive down the initialization time.
=> Add timer for generating mesh connectivity

flinter_rc.yml, src/case.f90
Helps troubleshooting when the simulation dies due to `ERROR: Parameter case.mesh_file missing from the case file` and gives hint that the json file is incorrect.
=> Add more intelligible error for when simulation dies instantly due to issue in the json file

src/simulation_components/simulation_component.f90
First step in the process of integrating things from CTR. Provides support for implementing a restart function for all simcomps.
Will be necessary as more functionality is moved to simcomps.
=> Add support for more advanced restarts for simcomps

configure.ac, doc/pages/user-guide/installation.md, m4/ax_openmp.m4
This adds the option to enable OpenMP flags from the configure scripts.
Currently this would enable OpenMP for the host code in the task-parallel hsmg formulation
=> Add enable/disable flags for OpenMP to configure

src/simulation_components/simcomp_executor.f90
The `simcomp_executor_add` subroutine now correctly allocates memory for the `simcomps` array.
=> fix mistake in simcomp allocation

.github/actions/flint/action.yml, .github/actions/flint/readme.md, .github/actions/flint/requirements-flint.txt, .github/workflows/check_lint.yml, .github/workflows/post_develop.yml, README.md
This pull request adds a linting action to execute the Flint linter on the specified directory. It also creates a post merge job for the develop branch that runs compilation checks and creates badges based on the results. Additionally, the badges for the linting score and compiler support are used to show the status of the code.
At the moment, the post merge job on develop should trigger whenever a PR is merged into develop succesfully.
Alternatively we can let it run as part of the nightly documentation update, this could be part of a nightly release job.
=> Add linting action and create post merge job for develop

src/io/fld_file.f90
Usecase for this is when some rank has 0 elements (which can be the case when one distributes a 2d mesh between ranks for example).
Perhaps we want to create a different communicator in this case, but this worked for 2d stats.
=> Make write of fld_file possible when not all ranks have an element 

src/.depends, src/common/craypat.F90, src/common/profiler.F90
This fixes the long broken interface to CrayPat, such that we can record Neko's profiler region to CrayPat profiles.
Example output:
```shell
Table 1:  Profile by Function Group and Function
Time% |     Time |     Imb. |  Imb. |    Calls | Group
|          |     Time | Time% |          |  Function
|          |          |       |          |   PE=HIDE
100.0% | 2.171254 |       -- |    -- | 50,102.0 | Total
|-----------------------------------------------------------------------
| 100.0% | 2.171254 |       -- |    -- | 50,102.0 | USER
||----------------------------------------------------------------------
||  24.9% | 0.540456 | 0.034187 |  6.8% |    347.0 | #8.HSMG_solve
||  21.2% | 0.460204 | 0.017860 |  4.3% |      5.0 | #3.Pressure_solve
||  13.6% | 0.295521 | 0.114109 | 31.8% |  7,054.0 …
```
=> Fix interface to CrayPat

src/common/bcknd/cpu/rhs_maker_cpu.f90, src/common/time_interpolator.f90
Optimizing loops with DO CONCURRENT for parallel execution for time_interpolator_scalar, rhs_maker_oifs_cpu, and scalar_rhs_maker_oifs_cpu
=> fix/parallelizing loop using DO CONCURRENT construct

src/sem/dofmap.f90
Somewhere among these changes dofmap brakes the use of midpoint deformations (and perhaps other things as well).
Perhaps source of issue on Dardel I noted earlier as well. 
Quick check to see the issue is to run the basic cyl_bl example.
=> Reverse dofmap to older version

bench/gs/driver.f90, bench/nekbone/driver.f90, contrib/average_field_in_space/average_field_in_space.f90, contrib/calc_lift_from_field/calc_lift_from_field.f90, contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90, examples/poisson/driver.f90, src/field/field.f90, src/fluid/fluid_plan1.f90, src/fluid/fluid_scheme.f90, src/io/chkp_file.f90, src/krylov/pc_hsmg.f90, src/math/schwarz.f90, src/mesh/point_zone_registry.f90, src/sem/dofmap.f90, tests/dofmap/dofmap_parallel.pf, tests/field/field_parallel.pf, tests/gather_scatter/gather_scatter_parallel.pf, tests/point_interpolation/point_interpolation_parallel.pf, tests/scratch_registry/test_scratch_registry.pf
Converts the dofmap constructor to a %init procedure, just like all other types have. Same for destructor. Bumps code style score.
Question, why is the dofmap destructor not called in some places. There is a comment in schwarz.f90 on line 155. I was generally surprised that I didn't have to refactor a single destructor call, excluding the one from the init.
=> Harmonize dofmap constructor and destructor, bump style

src/io/csv_file.f90
Fixes a bug in `csv_file_count_lines` that caused segfault without a proper error message if the csv file did not exist.
Noticed it when using probes with an input csv that did not exist. Since we call `csv_file_count_lines` before `csv_file_read` the usual safeguards were bypassed.
Perhaps could be good to cherry-pick this into `release` as well?
=> Check for existence of csv file in `count_lines`

src/fluid/fluid_scheme.f90
Currently parameters for the fluid source terms are not added correctly. Fixes the RBC examples and if anyone needs a forcing.
=> fix fluid source terms

.github/workflows/check_gnu.yml
This pull request updates the ROCm installation process to follow the instructions from the ROCm quick start guide, using the latest release. The previous method of adding the ROCm repository and installing the rocm-dev package has been replaced with downloading the amdgpu installation package and installing it using apt. This ensures that the latest release is used for the installation.
=> Update ROCm installation process

src/scalar/scalar_scheme.f90
The commit "scalar scheme message surpassed `LOG_SIZE`" fixes an issue where the specific heat capacity message resulted in a `Fortran runtime error: End of record` due to exceeding the log size. The commit updates the message to ensure it is displayed correctly.
=> Fix scalar scheme message for material properties

src/source_terms/source_term_handler.f90
I was having trouble appending source terms to a case with no source terms read from the JSON.
n_sources = size(this%source_terms) would return 1, then it would append the additional source term in position 2.
Then it would segfault trying to execute the unallocated source_terms(1).
=> Appending a source term to a case with no source terms

src/source_terms/boussinesq_source_term.f90
Wrong field is read into the start time variable
=> Fix boussinesq json parsing

configure.ac, contrib/Makefile.am, contrib/mesh_checker/Makefile.am, contrib/mesh_checker/mesh_checker.f90
Adds a mesh checker utility, currently in rudimentary and serial form, but already quite useful to detect what kind of zones one has in a mesh.
The idea is to add more diagnostics further on, and output associated fields as an option.
=> A mesh checker utility

.github/workflows/check_intel.yml
https://community.intel.com/t5/Blogs/Tech-Innovation/Tools/Deprecation-of-The-Intel-Fortran-Compiler-Classic-ifort/post/1541699
=> Remove deprecated compiler

src/math/math.f90
Uses `huge` to make glmin/max operation s tolerant to some processors having n=0.
=> glmin/max tolerant to n=0

contrib/mesh_checker/mesh_checker.f90
Adds mpi reduction on zone sizes to be able to run in parallel.
Adds deprecation warning for built-in mesh zones (non-periodic).
=> Add MPI support to mesh checker

doc/pages/user-guide/simcomps.md, src/simulation_components/simcomp_executor.f90, src/simulation_components/simulation_component.f90
- We can now add a fully initialized simcomp to the executor.
- We call finalize internally if needed instead of outside.
- Fix member accesibility.
- Add `fluid_output` as a compute control type.
=> Improvements to simulation components

src/bc/bc.f90, src/krylov/bcknd/cpu/bicgstab.f90, src/krylov/bcknd/cpu/cacg.f90, src/krylov/bcknd/cpu/cg.f90, src/krylov/bcknd/cpu/cg_coupled.f90, src/krylov/bcknd/cpu/cheby.f90, src/krylov/bcknd/cpu/gmres.f90, src/krylov/bcknd/cpu/pipecg.f90, src/krylov/bcknd/device/cg_device.f90, src/krylov/bcknd/device/cheby_device.F90, src/krylov/bcknd/device/fusedcg_cpld_device.F90, src/krylov/bcknd/device/fusedcg_device.F90, src/krylov/bcknd/device/gmres_device.F90, src/krylov/bcknd/device/pipecg_device.F90, src/krylov/bcknd/sx/cg_sx.f90, src/krylov/bcknd/sx/gmres_sx.f90, src/krylov/bcknd/sx/pipecg_sx.f90, src/krylov/krylov.f90, src/krylov/krylov_fctry.f90
- Fix issue #1329
Correct `intent(inout)` to `intent(in)` wherever applicable in `src/krylov/bcknd/**`
- `*_init()` functions
- `*_solve()` functions
- `*_solve_coupled()` functions
=> Fix proper usage of intent in Krylov solvers

src/mesh/aabb_tree.f90, src/mesh/search_tree/aabb.f90
Maybe it was possible to use the aabb directly previously, but I used it to create my global search tree of the whole domain for the global interpolation.
The sorting seems to have fixed a bug with some kind of race condition I had.
=> Add option to create aabb tree directly from aabb and fix sorting bug

src/krylov/krylov.f90, src/krylov/krylov_fctry.f90, src/krylov/precon.f90, src/krylov/precon_fctry.f90, src/les/les_model.f90, src/les/les_model_fctry.f90, src/wall_models/wall_model.f90, src/wall_models/wall_model_fctry.f90
Work around this bug in NVHPC:
https://forums.developer.nvidia.com/t/submodule-matching-error-of-declaration/211278 by removing target attribute from dummy args to module subroutine
=> nvhpc: workaround for submodule bug

src/fluid/fluid_scheme.f90
DoFs reported are not the degrees of freedom and if for one rank. This changes to the clobal number of grid points instead.
=> Fix reported "DoF"s

src/sem/dofmap.f90
Fixes an invalid edge numbering in dof numbering. 
This bug does **not** affect compilers with `INT64 = 8` (a so-called "byte" scheme)
=> Fix kind value dependent edge index

src/common/utils.f90
Adds a routine for reporting when an invalid type has been attempted to allocate for some base pointer type.
The idea is to use this in factories. The main bonus is the convenience of getting a list of valid types.
=> Add neko_type_error for reporting invalid type selection

src/gs/gather_scatter.f90
Adds the functionality of selecting either of the comp. and comm. backends for gather-scatter operations at runtime, e.g:
* Launch a host MPI backend on GPUs
`call gs%init(dof, comm_bcknd=GS_COMM_MPI)`
* Launch pure host MPI (despite Neko backend)
`call gs%init(dof, bcknd=GS_BCKND_CPU, comm_bcknd=GS_COMM_MPI)`
=> Make both comp. and comm. gs backends selectable

src/neko.f90
Move display of job info to an own subroutine, such that it can be reused e.g. in benchmarks like bk5, neko_opr or by high level interfaces
=> Move job info to an own subroutine

contrib/genmeshbox/genmeshbox.f90, contrib/prepart/prepart.f90, src/case.f90, src/comm/redist.f90, src/io/nmsh_file.f90, src/io/re2_file.f90, src/io/rea_file.f90, src/mesh/mesh.f90, tests/unit/dofmap/dofmap_parallel.pf, tests/unit/field/field_parallel.pf, tests/unit/gather_scatter/gather_scatter_parallel.pf, tests/unit/mean_field/mean_field_parallel.pf, tests/unit/mean_sqr_field/mean_sqr_field_parallel.pf, tests/unit/mesh/mesh_parallel.pf, tests/unit/point_interpolation/point_interpolation_parallel.pf, tests/unit/scratch_registry/test_scratch_registry.pf
This PR changes the nmsh/mesh handling of element indices, from local to global index. The global index is also retained during load balancing and redistribution (i.e vertex indices).
These changes introduces the possibility to write a mesh in parallel to a nmsh, e.g.  write out a mesh after load balancing, such that a restart could be performed (without scrambled data...) 
__Note__: No breaking changes, old meshes are still compatible 
_Todo_:
* `contrib/prepart ` needs some modifications before it can be used for "offline" load balancing in parallel
=> Change nmsh to use glb el index, allowing for parallel writes

src/fluid/fluid_scheme.f90
Reduce the dependency on JSON files by removing the parameters from the fluid_scheme class, simplifying the initialization and validation processes. This additionally limit the use of the json file to be only for initialization.
=> Remove unnecessary parameters from fluid_scheme class

src/common/bcknd/cpu/rhs_maker_cpu.f90
Besides the performance delta. This change also allows for `frtpx` to parallelise both loop nests.
=> Remove redundant sweep over all grid points for nab.eq.3

.github/workflows/check_format.yml, doc/pages/developer-guide/code-style.md
Adjust formatting rules to ensure no indentation is applied to case statements within select case blocks. Update the findent command to reflect these changes in the formatting process.
=> Stop indenting case lines in select statements

src/fluid/fluid_scheme_base.f90, src/fluid/fluid_scheme_incompressible.f90
Move the freeze fluid flag to the top level for better accessibility and management within the fluid scheme modules.
=> Lift freeze fluid flag to top level

src/bc/shear_stress.f90, src/bc/wall_model_bc.f90
The constructor was broken, because it was trying to init shear_stress_t from JSON, which failed when trying to locate the `value` keyword.
I add an init_from_components to shear_stress_t and use in the wall_model_bc_t constructor to fix things.
=> Fix wall model boundary condition constructor

src/gs/bcknd/device/cuda/gs.cu, src/gs/bcknd/device/cuda/gs_kernels.h, src/gs/bcknd/device/hip/gs.hip, src/gs/bcknd/device/hip/gs_kernels.h, tests/bench/gs/driver.f90, tests/unit/gather_scatter/gather_scatter_parallel.pf
- Supports `GS_OP_MIN`, `GS_OP_MAX` for `gs op` using CUDA and HIP
- Add unit tests for the added operators, in `tests/unit/gather_scatter`
- Add benchmark tests to `tests/bench/gs`
By running `tests/bench/gs`.
```
-------------Mesh-------------
Reading a binary Neko file box.nmsh
gdim = 3, nelements =     27000
Reading elements
Reading BC/zone data
Reading deformation data
Mesh read, setting up connectivity
Done setting up mesh and connectivity
Mesh and connectivity setup (excluding read) time (s): 93.528476
--------Gather-Scatter--------
Comm         :   Device MPI
Avg. internal:      2646000
Avg. external:            0
Backend      :          hip
GS_OP_ADD mean:   0.4491E-03, stddev:   0.3858E-05
GS_OP_MIN mean:   0.4492E-03, stddev:   0.3962E-05
GS_OP_MAX mean:   0.4490E-03, stddev: …
```
=> Atomic min max GS operator

doc/pages/user-guide/case-file.md, doc/pages/user-guide/user-file.md
There were some left-overs of documentation of boundary conditions, that are now redundant. 
The user file documentation also needed a few adaptations to the new bc json structure.
=> Remove redunant docs and update user file docs

contrib/mesh_checker/mesh_checker.f90, doc/pages/user-guide/case-file.md
Should be very handy for setting the zone_id for boundary conditions.
=> Add option to write a field with zone ids to mesh_checker

src/io/generic_file.f90
Maybe should look more into this, but fixes it for me at least. I think I access the get_counter before the file is initialized.
=> Counter is not always a proper number

contrib/genmeshbox/genmeshbox.f90, src/io/output_controller.f90
Increase field width from F10.6 to F12.6 to prevent overflow in genmeshbox and statistics logs in atmospheric cases.
=> Increase field width in logs to prevent overflow

src/multigrid/tree_amg_multigrid.f90
This fixes some more of the missing only statements. Related to #1754 and #1752
=> Fix missing only statements in tree_amg_multigrid.F90

src/multigrid/tree_amg_multigrid.f90
There was one last multigrid file missed in the previous PR. This should clean things up finally.
Related to #1752, #1754, #1755, #1756
=> Fix missing use only statements from tree_amg_multigrid.F90

doc/pages/user-guide/simcomps.md, src/les/dynamic_smagorinsky.f90, src/les/sigma.f90, src/les/smagorinsky.f90, src/les/vreman.f90, src/les/wale.f90
According to my personal experience, the extrapolation tends to be unstable in a lot of cases in the current LES setting, thus it's safe to set the default choice to be false. The point is a less accurate result is better than an unstable result.
=> make the default of extrapolation in les to be false

doc/pages/user-guide/user-file.md
Corrected a link in the documentation that disrupted the formatting of subsequent sections.
=> Fix formatting issue caused by link in documentation

src/Makefile.am
Enable external consumers of Neko to access more headers from the installed location.
=> Expose additional headers for external Neko consumers

.github/actions/setup_json-fortran/action.yml
Override the CMake policy to support deprecated versions of JSON-Fortran due to compatibility issues with the Intel compiler.
=> Override CMake policy for JSON-Fortran compatibility with Intel compiler

contrib/lint_format/format.sh, contrib/lint_format/lint.sh
Improve option parsing in scripts to support long options on macOS using gnu-getopt, with a fallback to BSD getopt. Additionally, implement reporting for unknown options.
=> Enhance option parsing for macOS compatibility

src/common/projection.f90
We should avoid allocating zero sized arrays, especially on devices, which might not support it
=> Don't allocate unecessary zero sized arrays

doc/pages/user-guide/simcomps.md, src/simulation_components/probes.F90
As the title says, adds a `start_time` to the probes. It is basically the same behavior as the statistics, with the intent to skip any transient behaviors in the beginning of a simulation, and start collecting probes after the given `start_time`.
It would be cool to have this stuff at the simcomp level but I am not feeling brave enough to mess with the time controllers right now... 
I propose to merge this if we are happy to get the functionality, and think bigger picture later :)
=> add start_time for probes

src/sem/bcknd/device/opencl/coef_kernel.cl
Fix invalid index in coef calculation for OpenCL backend (and make it more similar to the cuda/hip implementation)
=> Fix invalid index in coef (opencl)

src/math/bcknd/device/cuda/cuda_math.f90, src/math/bcknd/device/cuda/math.cu, src/math/bcknd/device/cuda/math_kernel.h, src/math/bcknd/device/device_math.F90, src/math/bcknd/device/hip/hip_math.f90, src/math/bcknd/device/hip/math.hip, src/math/bcknd/device/hip/math_kernel.h, src/math/bcknd/device/opencl/math.c, src/math/bcknd/device/opencl/math_kernel.cl, src/math/bcknd/device/opencl/opencl_math.f90, src/math/math.f90
- Adds the OpenCL kernel for masked_red_copy.
- Adds a new math routine, and the device kernels for it, called `masked_scatter_copy`, which is just like `masked_red_copy`, but applies the mask to the destination array. So you copy an array into a bigger array, with the mask telling to which elements to scatter the contiguous array. The need came in wall modelling code where I want to scatter the $\tau_w$ predictions stored in a vector to the boundary nodes of a field, which is used for processing.
=> Add masked_scatter_copy and masked_gather_copy for OpenCL

src/fluid/bcknd/device/pnpn_res_device.F90
This fixes the observed issues with the incompressible solver, strange flow patterns, divergence etc.
=> Fix invalid arg for pnpn_res OpenCL

src/bc/bcknd/device/opencl/facet_normal_kernel.cl, src/bc/bcknd/device/opencl/neumann_kernel.cl
Sorry I should seen this earlier when checking the neumann PR...
Due to Neko's way of JITting OpenCL kernels, we can't include none system header files in the `.cl` files without having runtime error thrown during the JIT phase.
=> Fix JIT error for facet normal and neumann kernel (OpenCL)

src/.depends, src/device/device.F90, src/neko.f90
Relocate the device count validation from `neko_init` to `device_init` to ensure proper checks are performed during device initialization.
=> Move device check to `device_init` function

src/source_terms/gradient_jump_penalty.f90
Make the penalty divided by the mass matrix before added to the source term.
=> fix a bug in GJP

doc/pages/user-guide/simcomps.md
Resolve a bug where a link was not terminated correctly causing large sections of the documenation to not be displayed correctly.
=> Fix bug in simcomp documentation

src/gs/bcknd/device/cuda/gs_kernels.h, src/gs/bcknd/device/device_mpi.c, src/gs/bcknd/device/hip/gs_kernels.h
gs_scatter could have two threads writing to the same place.
Incrementing a void pointer is apparently some gnu extension is I understand correctly and this would be more portable.
Continuing my search, sorry for the delay with interpolation.
=> Fix void pointer increment and race in gs_scatter

configure.ac, src/.depends, src/field/field_registry.f90, tests/unit/Makefile.am, tests/unit/field_registry/Makefile.in, tests/unit/field_registry/test_field_registry.pf
- Adds the possibility to add alieases to an exsiting field in the registry. For, example if there is a `field1` in the registry, we can add an alias for it, say `alias1`. Then if we call `get_field`, we can retrieve the field `field1` by both names: `field1` and `alias1`. I think this may be useful in contexts where we want have a field register under a particular name, but not take up extra memory. Material properties was an inspiration. If we have many scalars with the same properties, we still want fields like `saclar1_lambda` and `scalar2_lambda` to be in the registry. Otherwise, external objects somehow have to know that e.g. `scalar1_lambda` exists and `scalar2` uses it. With aliases, `scalar2` can just add an alias to the registry.
Internally the aliasing is done using an array of …
=> Add possibility to add aliases to field_register_t

doc/pages/appendices.md, doc/pages/user-guide/installation.md
Fixes #1729
Installation instructions for NVSHMEM we need to defer for now.
=> Add documentation for non-MPI based comm. backends

contrib/mesh_checker/mesh_checker.f90
For visualizing the zone indices, VisIt didn't like polynomial order 2.
=> Fix mesh_checker for boundary visualization with VisIt

src/device/cuda_intf.F90, src/device/device.F90, src/device/hip_intf.F90, src/device/opencl_intf.F90
This adds a `device_memset` that can be use to zero an array. The interface accepts both `sync` and `stream` arguments to allow for sync, without calling the costly `device_sync`
=> Add device memset interfaces

contrib/adios2_to_nek5000/adios2_to_nek5000.f90, contrib/average_field_in_space/average_field_in_space.f90, contrib/average_fields_in_time/average_fields_in_time.f90, contrib/calc_lift_from_field/calc_lift_from_field.f90, contrib/genmeshbox/genmeshbox.f90, contrib/map_to_equidistant_1d/map_to_equidistant_1d.f90, contrib/mesh_checker/mesh_checker.f90, contrib/postprocess_fluid_stats/postprocess_fluid_stats.f90, contrib/prepart/prepart.f90, contrib/psnr/psnr.f90, contrib/rea2nbin/rea2nbin.f90, examples/poisson/driver.f90, src/bc/bc.f90, src/case.f90, src/common/runtime_statistics.f90, src/fluid/flow_ic.f90, src/fluid/fluid_pnpn.f90, src/io/file.f90, src/io/output.f90, src/scalar/scalar_ic.f90, src/simulation.f90, src/simulation_components/probes.F90, src/source_terms/brinkman_source_term.f90, src/wall_models/wall_model.f90, tests/bench/ax/driver.f90, tests/bench/gs/driver.f90, tests/bench/nekbone/driver.f90
Removes the `= file_t()` constructor and adds the standard `%init` subroutine. As @MartinKarp pointed out, the = don't work well, and we use `%init` for everything else.
=> Refactor file_t constructor to a normal procedure

src/.depends, src/gs/bcknd/device/gs_device.F90, src/gs/bcknd/device/gs_device_mpi.F90
Add a memset after gs buffers are allocated. This is not needed for normal gather-scatter operations since they operate on the full length (m) for each call, however async. operations (as the ones done by global interpolation #1542, could be different).
This is similar to what was done in #1932, but here we use memset in the operating stream, thus reduce the numbers of global sync. points.
=> Add a device_memset before any gs operations (for extra safety)

src/gs/bcknd/device/gs_device_nccl.F90, src/gs/bcknd/device/gs_device_shmem.F90
Backport this fix from the MPI based gather-scatter backends to NCCL and SHMEM backends
=> Avoid host ptr being deallocated before memcpy is done

doc/pages/user-guide/case-file.md, src/krylov/krylov_fctry.f90
Closes issue #1620 by adding _ to some of the KSP type names. None used in examples, as far as I can see. Will break LES cases.
=> Add _ to ksp names

src/bc/facet_normal.f90
Fixes an issue when using a device backend, and the pnpn pressure surface terms are zero since no symmetry conditions are present. In this case, no facets will be marked, and `facet_normal_t` will, during init map a zero sized host array to the device, causing an invalid zero-sized `c_loc` call.  
To reproduce the issue, run e.g. the `turb_pipe` example
This is probably the cause of some of the face_normal related issues we have been observing with the device backend
=> Fix zero-sized array c_loc

src/krylov/krylov.f90, tests/regression/cylinder/test.sh, tests/regression/cylinder/test_easy.sh
Extends field name to the limit of our log size.
Should give more flexibility on the descriptive names.
Fixes ExtremeFLOW/neko#1974
=> Time-step log, Field variable name field too short

examples/api/c/cylinder.case, examples/api/pyneko/cylinder.case, examples/hemi/run.sh, examples/lid/lid.case, examples/lid/lid2d.case, examples/rayleigh_benard_cylinder/rayleigh.case, examples/turb_pipe/turb_pipe_source.case
The changes address multiple issues related to missing `case.time` objects in various case files, ensuring that the necessary time parameters are correctly structured within the JSON configuration. Additionally, the number of processors for the hemi case has been reduced to match other examples.
Fixes #1991, #1990, #1989, #1988, #1992, #1925
=> Fix missing case.time object and improve configuration files

src/fluid/fluid_scheme_incompressible.f90
Filling `mu_tot` during setuo might be a hack, but it prevents the current issues for non-stress formulations on devices.
This should also be safe for LES modellings, since mu_tot will be overwritten in the update parameter step
=> Make sure mu_tot is filled, fixes #1997

makeneko.in
This allows `makeneko` to compile user provided device files (`.cu/.hip`), to be called from the user provided `.f90` file. Callable routines in the device files must allow for C linkage, hence be inside a `extern "C"` block.
=> Add the possibility to compile .cu and .hip files with makeneko

flinter_rc.yml, src/source_terms/brinkman_source_term.f90
Add a new linter rule to ensure proper spacing after the `only` keyword.
=> Update linter to check for missing spaces after `only`

src/gs/bcknd/device/gs_device_mpi.F90, src/gs/bcknd/device/gs_device_nccl.F90, src/gs/bcknd/device/gs_device_shmem.F90, src/gs/gather_scatter.f90, src/gs/gs_comm.f90, src/gs/gs_mpi.f90
Revert new gs sync introduced in #2010, it did not solve any race, since both local and shared scatter operations is performed in the same stream, thus these can't overlap
=> Revert new gs sync introduced in #2010

makeneko.in
Small typo in makeneko for compiling on hip backends.
Probably good to cherry-pick into release as well!
=> Fix typo in makeneko or compiling with hip

src/device/device_config.h.in
Adds the extra precision type `real_xp` for usage in device kernels.
@njansson should this also be added to [src/api/neko.h.in](https://github.com/ExtremeFLOW/neko/blob/0d5f137f088fa1399b629bade601a73eea2d701d/src/api/neko.h.in#L7)?
=> Add extra precision type to device 

src/Makefile.am
This will put all headers installed by Neko under `prefix/include/neko/<internal_path>/`, instead of some of them being placed under `prefix/include`. Fortran modules will still be installed under the base include path.
=> Use 'nobase' installation for all headers except fortran modules

doc/pages/user-guide/user-file.md, src/io/bp_file.F90, src/io/fld_file.f90
For example if there're 4 scalars, only 3 of them are written to the output file because fld_file.f90 assumes there's always temperature at the 5th position.
=> Fix: missing multi-scalar output when no temperature output

flinter_rc.yml
Introduce a new linter rule to flag the use of equivalent boolean comparisons with .eqv. to promote better coding practices.
=> Add linter rule for .eqv. boolean comparisons

src/io/file.f90
Revert layout changes added by #2307, causing unnecessary warnings to be thrown
=> Only check for layout for BP files

src/math/vector.f90
Don't throw an error for zero sized vector allocations. This fixes #2062 (and probably more places after #2026).
Note: there's still enough checks in vector to avoid invalid launch configurations on devices for zero sized vectors.
=> Remove size check during vector allocation

src/api/neko_api_user.f90
=> Workaround for compiling the API with NAG in single precision

src/comm/parmetis.F90
Fix invalid type wrappers for parmetis, mainly assuming a 'byte scheme' for types (breaks on NAG)
=> Fix parmetis type wrappers

src/les/les_model.f90
The original option is directly ported from [Ntoukas et. al.](https://pdf.sciencedirectassets.com/320278/1-s2.0-S2590123024X00055/1-s2.0-S2590123025005043/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEFYaCXVzLWVhc3QtMSJHMEUCIFjSlZhtLKnLAI4JCf2ZM%2F5dzBXFqkTzIEt6HB6uL0Y9AiEAmRw800qFb6xwpTU0TMKgCA0BciVEKGqRkeOh1NnF7zkquwUIj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAFGgwwNTkwMDM1NDY4NjUiDKe91XX0an4alDp6DyqPBbSu0pueiUE7YBXULjs4bmqEwIi0%2F3TE%2BFACTsIljTTANFzt0L%2B05aYK26GXV3chHAchv396KZ1lffMANbhGdr%2Fi4yDgAhl%2BQe9nUEbRXVf5AN%2Bu7r14lXrBEtKKZY92FMfjybCDFprRDHzj1KqUEHsTg8l5DqcKZub2slpzomn7JFKLQ%2F%2BYkCiE0yV8y0liY2L6%2B6vz344bDLXdg8mX5yQ%2FMf5JvMQEt0YYyUUOCZBo3kkQNUkZE6TQVHvxMiWS9AxtZpXhrKXh6vDTFOZC64nZUHzoQ4Gr0a0H0idR7V5Tem6BVvdBZRc6ctAkt6AnyCB%2FU3VkK8YtlknsxBQP7mNab0NJ0KRczBkq6g%2BFszkk1G9UWH3Ia%2 …
=> Change the definition of the elementwise_average les delta field

doc/pages/appendices/governing-equations.md
some typos in the governing equations section. One potentially important remark: We use `fluid` for what is actually momentum.
=> some typos in governing equations

examples/programming/startup_and_json.f90, src/case.f90, src/common/json_utils.f90, src/fluid/fluid_pnpn.f90, src/fluid/fluid_scheme_incompressible.f90, src/les/dynamic_smagorinsky.f90, src/neko.f90, src/scalar/scalar_scheme.f90, src/scalar/scalars.f90, src/simulation_components/simcomp_executor.f90
I have observed that the object extraction invalidates the original json file object.
Also it have been superseeded by the `json_get_subdict` which is available through the `json_get` interface. The `json_get_subdict` does not show the same issues.
=> Remove json extract object

src/common/profiler.F90, src/common/runtime_statistics.f90
It gave very strange results since the Time-Step region was closed with no inputs. Meaning it was never closed at all.
=> Make the rt statistics support the timestep region. Was opened without ID and closed with no name or ID.

.github/workflows/check_nvidia.yml
Reverts ExtremeFLOW/neko#2110 due to `__cxa_` issues at link time...
=> Revert "Update CI to nvhpc 25.9"
